import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ulid } from 'ulid';
import { AuditService } from '../audit/audit.service.js';
import { TenantContextService } from '../tenant/tenant-context.service.js';
import { RoomStatus, type CreateRoomDto } from './dto/create-room.dto.js';
import type { UpdateRoomDto } from './dto/update-room.dto.js';

type RoomRow = { id:string; tenantId:string; branchId:string; branchCode:string; branchName:string; code:string; name:string; capacity:number|null; status:RoomStatus; notes:string|null; createdAt:Date; updatedAt:Date };
const columns = `r.id,r.tenant_id AS "tenantId",r.branch_id AS "branchId",b.code AS "branchCode",b.name AS "branchName",r.code,r.name,r.capacity,r.status,r.notes,r.created_at AS "createdAt",r.updated_at AS "updatedAt"`;
const select = `SELECT ${columns} FROM rooms r JOIN branches b ON b.tenant_id=r.tenant_id AND b.id=r.branch_id`;
const roomReferences = `SELECT 1 FROM classes WHERE tenant_id=$1 AND default_room_id=$2 UNION ALL SELECT 1 FROM schedules WHERE tenant_id=$1 AND room_id=$2 UNION ALL SELECT 1 FROM attendance_sessions WHERE tenant_id=$1 AND room_id=$2 LIMIT 1`;
const snapshot = (r:RoomRow) => ({ branchId:r.branchId, code:r.code, name:r.name, capacity:r.capacity, status:r.status, notes:r.notes });
const serialize = (r:RoomRow) => ({...r,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()});
function conflict(e:unknown){return typeof e==='object'&&e!==null&&'code'in e&&e.code==='23505'&&'constraint'in e&&e.constraint==='rooms_tenant_id_branch_id_code_key';}
@Injectable()
export class RoomsService {
 constructor(private readonly tenantContext:TenantContextService,private readonly audit:AuditService){}
 async list(branchId?:string){const {tenant,pool}=this.tenantContext.get();const values:[unknown,...unknown[]]=[tenant.tenantId];const where=['r.tenant_id=$1'];if(branchId){const branch=await pool.query('SELECT 1 FROM branches WHERE tenant_id=$1 AND id=$2',[tenant.tenantId,branchId]);if(!branch.rows[0])throw new NotFoundException('Branch not found');values.push(branchId);where.push(`r.branch_id=$${values.length}`);}const r=await pool.query<RoomRow>(`${select} WHERE ${where.join(' AND ')} ORDER BY r.name,r.id`,values);return r.rows.map(serialize);}
 async get(id:string){const {tenant,pool}=this.tenantContext.get();const r=await pool.query<RoomRow>(`${select} WHERE r.tenant_id=$1 AND r.id=$2`,[tenant.tenantId,id]);if(!r.rows[0])throw new NotFoundException('Room not found');return serialize(r.rows[0]);}
 async create(input:CreateRoomDto){const c=this.tenantContext.get();const client=await c.pool.connect();try{await client.query('BEGIN');const branch=await client.query(`SELECT id,status FROM branches WHERE tenant_id=$1 AND id=$2 FOR SHARE`,[c.tenant.tenantId,input.branchId]);if(!branch.rows[0])throw new NotFoundException('Branch not found');if(branch.rows[0].status==='DISABLED')throw new ConflictException('Branch is disabled');const id=ulid();await client.query(`INSERT INTO rooms(id,tenant_id,branch_id,code,name,capacity,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,c.tenant.tenantId,input.branchId,input.code.toUpperCase(),input.name,input.capacity??null,input.status??RoomStatus.ACTIVE,input.notes??null]);const row=(await client.query<RoomRow>(`${select} WHERE r.tenant_id=$1 AND r.id=$2`,[c.tenant.tenantId,id])).rows[0];await this.audit.recordTenant(client,{tenantId:c.tenant.tenantId,actorUserId:c.actorUserId,actorMembershipId:c.actorMembershipId,actorName:c.actorName,actorEmail:c.actorEmail,requestId:c.requestId,action:'room.created',entityType:'ROOM',entityId:row.id,after:snapshot(row)});await client.query('COMMIT');return serialize(row);}catch(e){await client.query('ROLLBACK').catch(()=>undefined);if(conflict(e))throw new ConflictException('Room code already exists in this branch');throw e;}finally{client.release();}}
 async update(id:string,input:UpdateRoomDto){const entries:[keyof UpdateRoomDto,string,(v:never)=>unknown][]=[['branchId','branch_id',(v:string)=>v],['code','code',(v:string)=>v.toUpperCase()],['name','name',(v:string)=>v],['capacity','capacity',(v:number|null)=>v],['status','status',(v:RoomStatus)=>v],['notes','notes',(v:string|null)=>v]];const fields:string[]=[];const vals:unknown[]=[];for(const[p,c,t]of entries)if(Object.hasOwn(input,p)&&input[p]!==undefined){vals.push(t(input[p]as never));fields.push(`${c}=$${vals.length+2}`);}if(!fields.length)throw new BadRequestException('At least one field is required');const c=this.tenantContext.get();const client=await c.pool.connect();try{await client.query('BEGIN');const old=await client.query<RoomRow>(`${select} WHERE r.tenant_id=$1 AND r.id=$2 FOR UPDATE`,[c.tenant.tenantId,id]);if(!old.rows[0])throw new NotFoundException('Room not found');if(input.branchId!==undefined){const b=await client.query(`SELECT status FROM branches WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,input.branchId]);if(!b.rows[0])throw new NotFoundException('Branch not found');if(b.rows[0].status==='DISABLED')throw new ConflictException('Branch is disabled');if(input.branchId!==old.rows[0].branchId&&(await client.query(roomReferences,[c.tenant.tenantId,id])).rows[0])throw new ConflictException('A referenced room cannot be moved to another branch');}await client.query(`UPDATE rooms SET ${fields.join(',')},updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,id,...vals]);const row=(await client.query<RoomRow>(`${select} WHERE r.tenant_id=$1 AND r.id=$2`,[c.tenant.tenantId,id])).rows[0];await this.audit.recordTenant(client,{tenantId:c.tenant.tenantId,actorUserId:c.actorUserId,actorMembershipId:c.actorMembershipId,actorName:c.actorName,actorEmail:c.actorEmail,requestId:c.requestId,action:'room.updated',entityType:'ROOM',entityId:id,before:snapshot(old.rows[0]),after:snapshot(row)});await client.query('COMMIT');return serialize(row);}catch(e){await client.query('ROLLBACK').catch(()=>undefined);if(conflict(e))throw new ConflictException('Room code already exists in this branch');throw e;}finally{client.release();}}
}
