import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { PoolClient, QueryResultRow } from 'pg';
import { ulid } from 'ulid';
import { AuditService } from '../audit/audit.service.js';
import { TenantContextService } from '../tenant/tenant-context.service.js';
import type { CreateAssessmentDto, ReplaceCriteriaDto, UpdateAssessmentDto } from './dto/assessment.dto.js';
import { ScoringMode } from './dto/assessment.dto.js';
import type { CorrectResultDto, ResultInputDto, SaveResultsDto } from './dto/result.dto.js';
import { ResultStatus } from './dto/result.dto.js';
import type { CreateProgressNoteDto, CreateProgressReportDto, UpdateProgressReportDto } from './dto/progress.dto.js';
import { formatScore, parseScore } from './score.js';
import { studentProgressSummary } from './progress-summary.js';

type Context = ReturnType<TenantContextService['get']>;
type Assessment = QueryResultRow & { id:string; tenantId:string; classId:string; type:string; title:string; description:string|null; scoringMode:ScoringMode; maxScore:string; assessmentDate:string|null; status:'DRAFT'|'PUBLISHED'|'ARCHIVED'; publishedAt:Date|null; publishedByUserId:string|null; createdAt:Date; updatedAt:Date };
type Criterion = QueryResultRow & { id:string; assessmentId:string; name:string; description:string|null; maxScore:string; displayOrder:number };
type Result = QueryResultRow & { id:string; assessmentId:string; studentId:string; enrollmentId:string; score:string|null; status:ResultStatus; comment:string|null; createdAt:Date; updatedAt:Date };
type CriterionResult = QueryResultRow & { criterionId:string; score:string; comment:string|null };
type Report = QueryResultRow & { id:string; studentId:string; enrollmentId:string; classId:string; title:string; periodStart:string; periodEnd:string; status:'DRAFT'|'PUBLISHED'|'SUPERSEDED'; teacherComment:string|null; strengths:string|null; areasForImprovement:string|null; nextSteps:string|null; snapshot:unknown; supersedesReportId:string|null; publishedAt:Date|null; publishedByUserId:string|null; createdAt:Date; updatedAt:Date };

const assessmentColumns = `a.id,a.tenant_id AS "tenantId",a.class_id AS "classId",a.type,a.title,a.description,a.scoring_mode AS "scoringMode",a.max_score::text AS "maxScore",a.assessment_date::text AS "assessmentDate",a.status,a.published_at AS "publishedAt",a.published_by_user_id AS "publishedByUserId",a.created_at AS "createdAt",a.updated_at AS "updatedAt"`;
const resultColumns = `r.id,r.assessment_id AS "assessmentId",r.student_id AS "studentId",r.enrollment_id AS "enrollmentId",r.score::text,r.status,r.comment,r.created_at AS "createdAt",r.updated_at AS "updatedAt"`;
const reportColumns = `r.id,r.student_id AS "studentId",r.enrollment_id AS "enrollmentId",r.class_id AS "classId",r.title,r.period_start::text AS "periodStart",r.period_end::text AS "periodEnd",r.status,r.teacher_comment AS "teacherComment",r.strengths,r.areas_for_improvement AS "areasForImprovement",r.next_steps AS "nextSteps",r.snapshot,r.supersedes_report_id AS "supersedesReportId",r.published_at AS "publishedAt",r.published_by_user_id AS "publishedByUserId",r.created_at AS "createdAt",r.updated_at AS "updatedAt"`;
const actor = (c:Context) => ({ tenantId:c.tenant.tenantId, actorUserId:c.actorUserId, actorMembershipId:c.actorMembershipId, actorName:c.actorName, actorEmail:c.actorEmail, requestId:c.requestId });
const positiveScore = (value:string, label='Score') => { const n=parseScore(value); if (n===null || n<=0) throw new BadRequestException(`${label} must be a positive decimal with at most 2 decimal places.`); return n; };
const boundedScore = (value:string, max:number, label='Score') => { const n=parseScore(value); if (n===null || n<0 || n>max) throw new BadRequestException(`${label} must be between 0 and ${formatScore(max)}.`); return n; };

@Injectable()
export class ProgressService {
  constructor(private readonly tenantContext:TenantContextService, private readonly audit:AuditService) {}

  async listAssessments(classId:string) {
    const {tenant,pool}=this.tenantContext.get();
    const rows=await pool.query<Assessment>(`SELECT ${assessmentColumns} FROM assessments a WHERE a.tenant_id=$1 AND a.class_id=$2 ORDER BY a.assessment_date DESC NULLS LAST,a.created_at DESC,a.id DESC`,[tenant.tenantId,classId]);
    return rows.rows;
  }
  async getAssessment(id:string) {
    const c=this.tenantContext.get(); const assessment=await this.assessment(c.pool,c.tenant.tenantId,id);
    const [criteria,results]=await Promise.all([
      c.pool.query<Criterion>(`SELECT id,assessment_id AS "assessmentId",name,description,max_score::text AS "maxScore",display_order AS "displayOrder" FROM assessment_criteria WHERE tenant_id=$1 AND assessment_id=$2 ORDER BY display_order,id`,[c.tenant.tenantId,id]),
      c.pool.query<Result & {studentName:string}>(`SELECT ${resultColumns},s.full_name AS "studentName" FROM assessment_results r JOIN students s ON s.tenant_id=r.tenant_id AND s.id=r.student_id WHERE r.tenant_id=$1 AND r.assessment_id=$2 ORDER BY s.full_name,r.id`,[c.tenant.tenantId,id]),
    ]);
    const criterionResults=results.rows.length ? await c.pool.query<CriterionResult & {assessmentResultId:string}>(`SELECT assessment_result_id AS "assessmentResultId",criterion_id AS "criterionId",score::text,comment FROM assessment_criterion_results WHERE tenant_id=$1 AND assessment_result_id=ANY($2::char(26)[]) ORDER BY assessment_result_id,criterion_id`,[c.tenant.tenantId,results.rows.map(r=>r.id)]) : {rows:[]};
    const byResult=new Map<string,CriterionResult[]>(); for(const row of criterionResults.rows){ const list=byResult.get(row.assessmentResultId)??[]; list.push(row); byResult.set(row.assessmentResultId,list); }
    return {...assessment,criteria:criteria.rows,results:results.rows.map(r=>({...r,criterionScores:byResult.get(r.id)??[]}))};
  }
  async createAssessment(classId:string,input:CreateAssessmentDto) {
    return this.transaction(async(client,c)=>{ await this.requireClass(client,c.tenant.tenantId,classId); this.validateAssessment(input.scoringMode,input.maxScore,input.criteria??[]); const id=ulid();
      await client.query(`INSERT INTO assessments(id,tenant_id,class_id,type,title,description,scoring_mode,max_score,assessment_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8::numeric,$9::date)`,[id,c.tenant.tenantId,classId,input.type,input.title.trim(),input.description??null,input.scoringMode,formatScore(positiveScore(input.maxScore,'Maximum score')),input.assessmentDate??null]);
      if(input.scoringMode===ScoringMode.RUBRIC) await this.insertCriteria(client,c.tenant.tenantId,id,input.criteria!);
      await this.audit.recordTenant(client,{...actor(c),action:'assessment.created',entityType:'ASSESSMENT',entityId:id,after:{classId,title:input.title,scoringMode:input.scoringMode}}); return id;
    }).then(id=>this.getAssessment(id));
  }
  async updateAssessment(id:string,input:UpdateAssessmentDto) {
    if(!Object.keys(input).length) throw new BadRequestException('At least one field is required.');
    await this.transaction(async(client,c)=>{ const old=await this.lockAssessment(client,c.tenant.tenantId,id); this.draft(old); const values:unknown[]=[c.tenant.tenantId,id]; const fields:string[]=[];
      for(const [key,column] of [['type','type'],['title','title'],['description','description'],['assessmentDate','assessment_date']] as const) if(input[key]!==undefined){values.push(input[key]);fields.push(`${column}=$${values.length}${key==='assessmentDate'?'::date':''}`);}
      if(input.maxScore!==undefined){ const max=formatScore(positiveScore(input.maxScore,'Maximum score')); if(old.scoringMode===ScoringMode.RUBRIC){ const sum=await client.query<{sum:string}>(`SELECT COALESCE(SUM(max_score),0)::text AS sum FROM assessment_criteria WHERE tenant_id=$1 AND assessment_id=$2`,[c.tenant.tenantId,id]); if(parseScore(sum.rows[0].sum)!==parseScore(max!)) throw new BadRequestException('Maximum score must equal the rubric criteria total.'); } values.push(max);fields.push(`max_score=$${values.length}::numeric`); }
      const updated=await client.query<Assessment>(`UPDATE assessments a SET ${fields.join(',')},updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2 RETURNING ${assessmentColumns}`.replace('a.id','id').replaceAll('a.',''),values);
      await this.audit.recordTenant(client,{...actor(c),action:'assessment.updated',entityType:'ASSESSMENT',entityId:id,before:old,after:updated.rows[0]});
    }); return this.getAssessment(id);
  }
  async replaceCriteria(id:string,input:ReplaceCriteriaDto) {
    await this.transaction(async(client,c)=>{ const assessment=await this.lockAssessment(client,c.tenant.tenantId,id); this.draft(assessment); if(assessment.scoringMode!==ScoringMode.RUBRIC) throw new ConflictException('Only rubric assessments have criteria.'); const total=formatScore(input.criteria.reduce((sum,item)=>sum+positiveScore(item.maxScore,'Criterion maximum score'),0))!; await client.query('DELETE FROM assessment_criteria WHERE tenant_id=$1 AND assessment_id=$2',[c.tenant.tenantId,id]); await this.insertCriteria(client,c.tenant.tenantId,id,input.criteria); await client.query('UPDATE assessments SET max_score=$3::numeric,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2',[c.tenant.tenantId,id,total]); await this.audit.recordTenant(client,{...actor(c),action:'assessment.criteria_replaced',entityType:'ASSESSMENT',entityId:id,after:{criteriaCount:input.criteria.length}}); }); return this.getAssessment(id);
  }
  async gradebook(id:string) {
    const c=this.tenantContext.get(),assessment=await this.assessment(c.pool,c.tenant.tenantId,id);
    const [criteria,rows]=await Promise.all([
      this.criteria(c.pool,c.tenant.tenantId,id),
      c.pool.query(`SELECT e.id AS "enrollmentId",e.status AS "enrollmentStatus",s.id AS "studentId",s.code AS "studentCode",s.full_name AS "studentName",r.id AS "resultId",r.status AS "resultStatus",r.score::text,r.comment FROM students s LEFT JOIN assessment_results r ON r.tenant_id=s.tenant_id AND r.assessment_id=$2 AND r.student_id=s.id JOIN LATERAL (SELECT candidate.id,candidate.status FROM enrollments candidate WHERE candidate.tenant_id=s.tenant_id AND candidate.student_id=s.id AND candidate.class_id=$3 AND candidate.status<>'TRIAL' ORDER BY (candidate.id=r.enrollment_id) DESC,CASE WHEN candidate.status IN ('ACTIVE','PAUSED') THEN 0 ELSE 1 END,candidate.enrolled_at DESC,candidate.id DESC LIMIT 1) e ON TRUE WHERE s.tenant_id=$1 ORDER BY s.full_name,s.id`,[c.tenant.tenantId,id,assessment.classId]),
    ]);
    const resultIds=rows.rows.flatMap((r:any)=>r.resultId?[r.resultId]:[]);
    const criterionRows=resultIds.length?await c.pool.query(`SELECT assessment_result_id AS "resultId",criterion_id AS "criterionId",score::text,comment FROM assessment_criterion_results WHERE tenant_id=$1 AND assessment_result_id=ANY($2::char(26)[]) ORDER BY assessment_result_id,criterion_id`,[c.tenant.tenantId,resultIds]):{rows:[]};
    const byResult=new Map<string,unknown[]>(); for(const row of criterionRows.rows as any[]){const list=byResult.get(row.resultId)??[];list.push(row);byResult.set(row.resultId,list);}
    return {assessment,criteria,results:rows.rows.map((row:any)=>({id:row.resultId??null,studentId:row.studentId,studentCode:row.studentCode,studentName:row.studentName,enrollmentId:row.enrollmentId,enrollmentStatus:row.enrollmentStatus,status:row.resultStatus??null,score:row.score??null,comment:row.comment??null,criterionScores:row.resultId?byResult.get(row.resultId)??[]:[]}))};
  }
  async studentProgress(studentId:string) {
    const c=this.tenantContext.get(); await this.requireStudent(c.pool,c.tenant.tenantId,studentId);
    const [summary,assessments]=await Promise.all([
      studentProgressSummary(c.pool,c.tenant.tenantId,studentId),
      c.pool.query(`SELECT a.id AS "assessmentId",a.class_id AS "classId",a.title,a.type,a.assessment_date::text AS "assessmentDate",a.status AS "assessmentStatus",a.max_score::text AS "maxScore",r.id AS "resultId",r.score::text,r.status AS "resultStatus",r.comment FROM assessment_results r JOIN assessments a ON a.tenant_id=r.tenant_id AND a.id=r.assessment_id WHERE r.tenant_id=$1 AND r.student_id=$2 ORDER BY a.assessment_date DESC NULLS LAST,a.created_at DESC,a.id DESC`,[c.tenant.tenantId,studentId]),
    ]);
    return {summary,assessments:assessments.rows};
  }
  async saveResults(id:string,input:SaveResultsDto) {
    const seen=new Set<string>(); if(!input.results.length) throw new BadRequestException('At least one result is required.'); for(const item of input.results){if(seen.has(item.studentId)) throw new BadRequestException('A student may appear only once.'); seen.add(item.studentId);}
    await this.transaction(async(client,c)=>{ const assessment=await this.lockAssessment(client,c.tenant.tenantId,id); this.draft(assessment); const criteria=await this.criteria(client,c.tenant.tenantId,id); const enrollments=await client.query<{id:string;studentId:string}>(`SELECT id,student_id AS "studentId" FROM enrollments WHERE tenant_id=$1 AND class_id=$2 AND student_id=ANY($3::char(26)[]) AND status IN ('PENDING','ACTIVE','PAUSED','COMPLETED','WITHDRAWN') ORDER BY student_id,CASE WHEN status IN ('ACTIVE','PAUSED') THEN 0 ELSE 1 END,enrolled_at DESC`,[c.tenant.tenantId,assessment.classId,[...seen]]); const enrollmentByStudent=new Map<string,string>(); for(const e of enrollments.rows) if(!enrollmentByStudent.has(e.studentId)) enrollmentByStudent.set(e.studentId,e.id); if(enrollmentByStudent.size!==seen.size) throw new BadRequestException('Every graded student must have a non-trial enrollment in the assessment class.');
      for(const item of input.results) await this.upsertResult(client,c.tenant.tenantId,assessment,criteria,item,enrollmentByStudent.get(item.studentId)!);
      await this.audit.recordTenant(client,{...actor(c),action:'assessment.gradebook_saved',entityType:'ASSESSMENT',entityId:id,after:{resultCount:input.results.length}});
    }); return this.getAssessment(id);
  }
  async publishAssessment(id:string){ await this.changeAssessmentStatus(id,'PUBLISHED'); return this.getAssessment(id); }
  async archiveAssessment(id:string){ await this.changeAssessmentStatus(id,'ARCHIVED'); return this.getAssessment(id); }
  async correctResult(id:string,input:CorrectResultDto){
    await this.transaction(async(client,c)=>{ const ref=await client.query<{assessmentId:string}>(`SELECT assessment_id AS "assessmentId" FROM assessment_results WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,id]); if(!ref.rows[0]) throw new NotFoundException('Published result not found'); await this.lockAssessment(client,c.tenant.tenantId,ref.rows[0].assessmentId); const row=await client.query<Result & {scoringMode:ScoringMode;maxScore:string;assessmentStatus:string}>(`SELECT ${resultColumns},a.scoring_mode AS "scoringMode",a.max_score::text AS "maxScore",a.status AS "assessmentStatus" FROM assessment_results r JOIN assessments a ON a.tenant_id=r.tenant_id AND a.id=r.assessment_id WHERE r.tenant_id=$1 AND r.id=$2 FOR UPDATE OF r`,[c.tenant.tenantId,id]); const old=row.rows[0]; if(!old||old.assessmentStatus!=='PUBLISHED') throw new NotFoundException('Published result not found'); const criteria=await this.criteria(client,c.tenant.tenantId,old.assessmentId); const before=await this.resultSnapshot(client,c.tenant.tenantId,old); const status=input.status??old.status; const merged:ResultInputDto={studentId:old.studentId,enrollmentId:old.enrollmentId,status,score:status===ResultStatus.EXEMPT?undefined:input.score??old.score??undefined,comment:input.comment===undefined?old.comment:input.comment,criterionScores:status===ResultStatus.EXEMPT?undefined:input.criterionScores}; const computed=this.validateResult({scoringMode:old.scoringMode,maxScore:old.maxScore} as Assessment,criteria,merged);
      await client.query(`UPDATE assessment_results SET status=$3,score=$4::numeric,comment=$5,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,id,merged.status,computed.score,merged.comment??null]); await client.query('DELETE FROM assessment_criterion_results WHERE tenant_id=$1 AND assessment_result_id=$2',[c.tenant.tenantId,id]); if(computed.criteria.length) await this.insertCriterionResults(client,c.tenant.tenantId,id,computed.criteria); const now=(await client.query<Result>(`SELECT ${resultColumns} FROM assessment_results r WHERE r.tenant_id=$1 AND r.id=$2`,[c.tenant.tenantId,id])).rows[0]; const after=await this.resultSnapshot(client,c.tenant.tenantId,now); if(JSON.stringify(before)===JSON.stringify(after)) throw new BadRequestException('Correction must change the result.'); await client.query(`INSERT INTO assessment_result_revisions(id,tenant_id,assessment_result_id,before_snapshot,after_snapshot,reason,actor_user_id,actor_membership_id,created_at) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7,$8,clock_timestamp())`,[ulid(),c.tenant.tenantId,id,JSON.stringify(before),JSON.stringify(after),input.reason.trim(),c.actorUserId??null,c.actorMembershipId??null]); await this.audit.recordTenant(client,{...actor(c),action:'assessment.result_corrected',entityType:'ASSESSMENT_RESULT',entityId:id,before,after,reason:input.reason.trim()});
    }); return this.getResult(id);
  }
  async resultHistory(id:string){ const c=this.tenantContext.get(); await this.getResult(id); return (await c.pool.query(`SELECT id,before_snapshot AS "beforeSnapshot",after_snapshot AS "afterSnapshot",reason,actor_user_id AS "actorUserId",actor_membership_id AS "actorMembershipId",created_at AS "createdAt" FROM assessment_result_revisions WHERE tenant_id=$1 AND assessment_result_id=$2 ORDER BY created_at,id`,[c.tenant.tenantId,id])).rows; }
  async getResult(id:string){ const c=this.tenantContext.get(); const row=await c.pool.query<Result>(`SELECT ${resultColumns} FROM assessment_results r WHERE r.tenant_id=$1 AND r.id=$2`,[c.tenant.tenantId,id]); if(!row.rows[0]) throw new NotFoundException('Result not found'); return this.resultSnapshot(c.pool,c.tenant.tenantId,row.rows[0]); }

  async createNote(studentId:string,input:CreateProgressNoteDto){ const c=this.tenantContext.get(); const id=ulid(); if(input.enrollmentId||input.classId){ const valid=await c.pool.query(`SELECT 1 FROM enrollments WHERE tenant_id=$1 AND student_id=$2 AND ($3::char(26) IS NULL OR id=$3) AND ($4::char(26) IS NULL OR class_id=$4)`,[c.tenant.tenantId,studentId,input.enrollmentId??null,input.classId??null]); if(!valid.rows[0]) throw new BadRequestException('Enrollment or class does not belong to the student.'); } else await this.requireStudent(c.pool,c.tenant.tenantId,studentId); await this.transaction(async(client)=>{ await client.query(`INSERT INTO progress_notes(id,tenant_id,student_id,enrollment_id,class_id,content,author_user_id,author_membership_id,author_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,c.tenant.tenantId,studentId,input.enrollmentId??null,input.classId??null,input.content.trim(),c.actorUserId??null,c.actorMembershipId??null,c.actorName??null]); await this.audit.recordTenant(client,{...actor(c),action:'progress.note_added',entityType:'PROGRESS_NOTE',entityId:id,after:{studentId,enrollmentId:input.enrollmentId??null,classId:input.classId??null}}); }); return (await c.pool.query(`SELECT id,student_id AS "studentId",enrollment_id AS "enrollmentId",class_id AS "classId",content,author_name AS "authorName",created_at AS "createdAt" FROM progress_notes WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,id])).rows[0]; }
  async notes(studentId:string){ const c=this.tenantContext.get(); await this.requireStudent(c.pool,c.tenant.tenantId,studentId); return (await c.pool.query(`SELECT id,student_id AS "studentId",enrollment_id AS "enrollmentId",class_id AS "classId",content,author_name AS "authorName",created_at AS "createdAt" FROM progress_notes WHERE tenant_id=$1 AND student_id=$2 ORDER BY created_at DESC,id DESC`,[c.tenant.tenantId,studentId])).rows; }
  summary(studentId:string,classId?:string,periodStart?:string,periodEnd?:string){ const c=this.tenantContext.get(); return studentProgressSummary(c.pool,c.tenant.tenantId,studentId,{classId,periodStart,periodEnd}); }

  async createReport(input:CreateProgressReportDto){ const id=ulid(); await this.transaction(async(client,c)=>{ const enrollment=await this.enrollment(client,c.tenant.tenantId,input.enrollmentId,input.studentId); this.validatePeriod(input.periodStart,input.periodEnd); await client.query(`INSERT INTO progress_reports(id,tenant_id,student_id,enrollment_id,class_id,title,period_start,period_end,teacher_comment,strengths,areas_for_improvement,next_steps) VALUES($1,$2,$3,$4,$5,$6,$7::date,$8::date,$9,$10,$11,$12)`,[id,c.tenant.tenantId,input.studentId,input.enrollmentId,enrollment.classId,input.title.trim(),input.periodStart,input.periodEnd,input.teacherComment??null,input.strengths??null,input.areasForImprovement??null,input.nextSteps??null]); await this.audit.recordTenant(client,{...actor(c),action:'progress_report.created',entityType:'PROGRESS_REPORT',entityId:id,after:{studentId:input.studentId,enrollmentId:input.enrollmentId}}); }); return this.getReport(id); }
  async updateReport(id:string,input:UpdateProgressReportDto){ if(!Object.keys(input).length) throw new BadRequestException('At least one field is required.'); await this.transaction(async(client,c)=>{ const old=await this.lockReport(client,c.tenant.tenantId,id); this.draftReport(old); const start=input.periodStart??old.periodStart,end=input.periodEnd??old.periodEnd; this.validatePeriod(start,end); const map={title:'title',periodStart:'period_start',periodEnd:'period_end',teacherComment:'teacher_comment',strengths:'strengths',areasForImprovement:'areas_for_improvement',nextSteps:'next_steps'} as const; const values:unknown[]=[c.tenant.tenantId,id]; const fields:string[]=[]; for(const [key,col] of Object.entries(map) as [keyof UpdateProgressReportDto,string][]) if(input[key]!==undefined){values.push(input[key]);fields.push(`${col}=$${values.length}${key==='periodStart'||key==='periodEnd'?'::date':''}`);} await client.query(`UPDATE progress_reports SET ${fields.join(',')},updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2`,values); await this.audit.recordTenant(client,{...actor(c),action:'progress_report.updated',entityType:'PROGRESS_REPORT',entityId:id,before:old,after:{...old,...input}}); }); return this.getReport(id); }
  async previewReport(id:string){ const c=this.tenantContext.get(); const report=await this.report(c.pool,c.tenant.tenantId,id); const summary=await studentProgressSummary(c.pool,c.tenant.tenantId,report.studentId,{classId:report.classId,periodStart:report.periodStart,periodEnd:report.periodEnd}); return this.reportSnapshot(c.pool,c.tenant.tenantId,report,summary); }
  async publishReport(id:string){ await this.transaction(async(client,c)=>{ const report=await this.lockReport(client,c.tenant.tenantId,id); this.draftReport(report); if(report.supersedesReportId){ const previous=await this.lockReport(client,c.tenant.tenantId,report.supersedesReportId); if(previous.status!=='PUBLISHED') throw new ConflictException('The superseded report is no longer published.'); await client.query(`UPDATE progress_reports SET status='SUPERSEDED',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,previous.id]); await this.audit.recordTenant(client,{...actor(c),action:'progress_report.superseded',entityType:'PROGRESS_REPORT',entityId:previous.id,before:{status:'PUBLISHED'},after:{status:'SUPERSEDED',replacementReportId:id}}); } const summary=await studentProgressSummary(client,c.tenant.tenantId,report.studentId,{classId:report.classId,periodStart:report.periodStart,periodEnd:report.periodEnd}); const snapshot=await this.reportSnapshot(client,c.tenant.tenantId,report,summary); await client.query(`UPDATE progress_reports SET status='PUBLISHED',snapshot=$3::jsonb,published_at=CURRENT_TIMESTAMP,published_by_user_id=$4,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,id,JSON.stringify(snapshot),c.actorUserId??null]); await this.audit.recordTenant(client,{...actor(c),action:'progress_report.published',entityType:'PROGRESS_REPORT',entityId:id,after:snapshot}); }); return this.getReport(id); }
  async replaceReport(id:string,input:UpdateProgressReportDto){ const replacement=await this.transaction(async(client,c)=>{ const old=await this.lockReport(client,c.tenant.tenantId,id); if(old.status!=='PUBLISHED') throw new ConflictException('Only published reports can be replaced.'); await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`progress-report-replacement:${c.tenant.tenantId}:${id}`]); const existing=await client.query('SELECT 1 FROM progress_reports WHERE tenant_id=$1 AND supersedes_report_id=$2 FOR UPDATE',[c.tenant.tenantId,id]); if(existing.rows[0]) throw new ConflictException('Report already has a replacement.'); const merged={...old,...input}; this.validatePeriod(merged.periodStart,merged.periodEnd); const newId=ulid(); await client.query(`INSERT INTO progress_reports(id,tenant_id,student_id,enrollment_id,class_id,title,period_start,period_end,teacher_comment,strengths,areas_for_improvement,next_steps,supersedes_report_id) VALUES($1,$2,$3,$4,$5,$6,$7::date,$8::date,$9,$10,$11,$12,$13)`,[newId,c.tenant.tenantId,old.studentId,old.enrollmentId,old.classId,merged.title,merged.periodStart,merged.periodEnd,merged.teacherComment,merged.strengths,merged.areasForImprovement,merged.nextSteps,id]); await this.audit.recordTenant(client,{...actor(c),action:'progress_report.created',entityType:'PROGRESS_REPORT',entityId:newId,before:{supersededReportId:id},after:{replacementReportId:newId}}); return newId; }); return this.getReport(replacement); }
  async reportHistory(studentId:string){ const c=this.tenantContext.get(); await this.requireStudent(c.pool,c.tenant.tenantId,studentId); return (await c.pool.query<Report>(`SELECT ${reportColumns} FROM progress_reports r WHERE r.tenant_id=$1 AND r.student_id=$2 ORDER BY r.created_at DESC,r.id DESC`,[c.tenant.tenantId,studentId])).rows; }
  async getReport(id:string){ const c=this.tenantContext.get(); return this.report(c.pool,c.tenant.tenantId,id); }

  private async changeAssessmentStatus(id:string,status:'PUBLISHED'|'ARCHIVED'){ await this.transaction(async(client,c)=>{ const old=await this.lockAssessment(client,c.tenant.tenantId,id); if(status==='PUBLISHED'&&old.status!=='DRAFT') throw new ConflictException('Only draft assessments can be published.'); if(status==='PUBLISHED'){ const criteria=await this.criteria(client,c.tenant.tenantId,id); this.validateAssessment(old.scoringMode,old.maxScore,criteria); const results=await client.query<Result>(`SELECT ${resultColumns} FROM assessment_results r WHERE r.tenant_id=$1 AND r.assessment_id=$2 FOR UPDATE`,[c.tenant.tenantId,id]); for(const result of results.rows){ const snapshot=await this.resultSnapshot(client,c.tenant.tenantId,result); this.validateResult(old,criteria,{studentId:result.studentId,status:result.status,score:result.score??undefined,comment:result.comment,criterionScores:snapshot.criterionScores}); }} if(status==='ARCHIVED'&&old.status!=='PUBLISHED') throw new ConflictException('Only published assessments can be archived.'); await client.query(`UPDATE assessments SET status=$3,published_at=CASE WHEN $3='PUBLISHED' THEN CURRENT_TIMESTAMP ELSE published_at END,published_by_user_id=CASE WHEN $3='PUBLISHED' THEN $4 ELSE published_by_user_id END,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2`,[c.tenant.tenantId,id,status,c.actorUserId??null]); await this.audit.recordTenant(client,{...actor(c),action:`assessment.${status.toLowerCase()}`,entityType:'ASSESSMENT',entityId:id,before:{status:old.status},after:{status}}); }); }
  private validateAssessment(mode:ScoringMode,max:string,criteria:Array<{name:string;maxScore:string}>){ const maxCents=positiveScore(max,'Maximum score'); if(mode===ScoringMode.SIMPLE&&criteria.length) throw new BadRequestException('Simple assessments cannot have criteria.'); if(mode===ScoringMode.RUBRIC){if(!criteria.length) throw new BadRequestException('Rubric assessments require criteria.'); const sum=criteria.reduce((n,c)=>n+positiveScore(c.maxScore,'Criterion maximum score'),0); if(sum!==maxCents) throw new BadRequestException('Maximum score must equal the rubric criteria total.');} }
  private async upsertResult(client:PoolClient,tenantId:string,a:Assessment,criteria:Criterion[],item:ResultInputDto,enrollmentId:string){ if(item.enrollmentId&&item.enrollmentId!==enrollmentId) throw new BadRequestException('Enrollment does not match the student and assessment class.'); const computed=this.validateResult(a,criteria,item); const result=await client.query<{id:string}>(`INSERT INTO assessment_results(id,tenant_id,assessment_id,student_id,enrollment_id,score,status,comment) VALUES($1,$2,$3,$4,$5,$6::numeric,$7,$8) ON CONFLICT(tenant_id,assessment_id,student_id) DO UPDATE SET enrollment_id=EXCLUDED.enrollment_id,score=EXCLUDED.score,status=EXCLUDED.status,comment=EXCLUDED.comment,updated_at=CURRENT_TIMESTAMP RETURNING id`,[ulid(),tenantId,a.id,item.studentId,enrollmentId,computed.score,item.status,item.comment??null]); await client.query('DELETE FROM assessment_criterion_results WHERE tenant_id=$1 AND assessment_result_id=$2',[tenantId,result.rows[0].id]); if(computed.criteria.length) await this.insertCriterionResults(client,tenantId,result.rows[0].id,computed.criteria); }
  private validateResult(a:Pick<Assessment,'scoringMode'|'maxScore'>,criteria:Criterion[],item:ResultInputDto){ if(item.status===ResultStatus.EXEMPT){if(item.score!==undefined||item.criterionScores?.length) throw new BadRequestException('Exempt results cannot have scores.'); return {score:null,criteria:[]};} if(a.scoringMode===ScoringMode.SIMPLE){if(item.score===undefined) throw new BadRequestException('A score is required for simple assessments.'); if(item.criterionScores?.length) throw new BadRequestException('Simple assessments cannot have criterion scores.'); return {score:formatScore(boundedScore(item.score,positiveScore(a.maxScore))),criteria:[]};} const given=item.criterionScores??[]; if(item.score!==undefined) throw new BadRequestException('Rubric scores are derived from criteria.'); if(given.length!==criteria.length||new Set(given.map(x=>x.criterionId)).size!==criteria.length) throw new BadRequestException('Every rubric criterion must be scored exactly once.'); const byId=new Map(criteria.map(c=>[c.id,c])); const normalized=given.map(x=>{const criterion=byId.get(x.criterionId);if(!criterion) throw new BadRequestException('Unknown rubric criterion.'); return {...x,score:formatScore(boundedScore(x.score,positiveScore(criterion.maxScore),'Criterion score'))!};}); return {score:formatScore(normalized.reduce((sum,x)=>sum+parseScore(x.score)!,0)),criteria:normalized}; }
  private async insertCriteria(client:PoolClient,tenantId:string,assessmentId:string,criteria:Array<{name:string;description?:string|null;maxScore:string}>){for(const [i,c] of criteria.entries()) await client.query(`INSERT INTO assessment_criteria(id,tenant_id,assessment_id,name,description,max_score,display_order) VALUES($1,$2,$3,$4,$5,$6::numeric,$7)`,[ulid(),tenantId,assessmentId,c.name.trim(),c.description??null,formatScore(positiveScore(c.maxScore)),i]);}
  private async insertCriterionResults(client:PoolClient,tenantId:string,resultId:string,items:Array<{criterionId:string;score:string;comment?:string|null}>){for(const x of items) await client.query(`INSERT INTO assessment_criterion_results(id,tenant_id,assessment_result_id,criterion_id,score,comment) VALUES($1,$2,$3,$4,$5::numeric,$6)`,[ulid(),tenantId,resultId,x.criterionId,x.score,x.comment??null]);}
  private async criteria(q:{query:PoolClient['query']},tenantId:string,id:string){return (await q.query<Criterion>(`SELECT id,assessment_id AS "assessmentId",name,description,max_score::text AS "maxScore",display_order AS "displayOrder" FROM assessment_criteria WHERE tenant_id=$1 AND assessment_id=$2 ORDER BY display_order,id`,[tenantId,id])).rows;}
  private async resultSnapshot(q:{query:PoolClient['query']},tenantId:string,result:Result){const criteria=await q.query<CriterionResult>(`SELECT criterion_id AS "criterionId",score::text,comment FROM assessment_criterion_results WHERE tenant_id=$1 AND assessment_result_id=$2 ORDER BY criterion_id`,[tenantId,result.id]);return {...result,criterionScores:criteria.rows};}
  private async assessment(q:{query:PoolClient['query']},tenantId:string,id:string){const r=await q.query<Assessment>(`SELECT ${assessmentColumns} FROM assessments a WHERE a.tenant_id=$1 AND a.id=$2`,[tenantId,id]);if(!r.rows[0])throw new NotFoundException('Assessment not found');return r.rows[0];}
  private async lockAssessment(q:{query:PoolClient['query']},tenantId:string,id:string){const r=await q.query<Assessment>(`SELECT ${assessmentColumns} FROM assessments a WHERE a.tenant_id=$1 AND a.id=$2 FOR UPDATE`,[tenantId,id]);if(!r.rows[0])throw new NotFoundException('Assessment not found');return r.rows[0];}
  private draft(a:Assessment){if(a.status!=='DRAFT')throw new ConflictException('Only draft assessments can be edited.');}
  private async report(q:{query:PoolClient['query']},tenantId:string,id:string){const r=await q.query<Report>(`SELECT ${reportColumns} FROM progress_reports r WHERE r.tenant_id=$1 AND r.id=$2`,[tenantId,id]);if(!r.rows[0])throw new NotFoundException('Progress report not found');return r.rows[0];}
  private async lockReport(q:{query:PoolClient['query']},tenantId:string,id:string){const r=await q.query<Report>(`SELECT ${reportColumns} FROM progress_reports r WHERE r.tenant_id=$1 AND r.id=$2 FOR UPDATE`,[tenantId,id]);if(!r.rows[0])throw new NotFoundException('Progress report not found');return r.rows[0];}
  private draftReport(r:Report){if(r.status!=='DRAFT')throw new ConflictException('Only draft reports can be edited.');}
  private async reportSnapshot(q:{query:PoolClient['query']},tenantId:string,report:Report,summary:unknown){
    const [context,assessments]=await Promise.all([
      q.query(`SELECT s.id AS "studentId",s.code AS "studentCode",s.full_name AS "studentName",e.id AS "enrollmentId",c.id AS "classId",c.code AS "classCode",c.name AS "className",co.id AS "courseId",co.code AS "courseCode",co.name AS "courseName",cl.id AS "courseLevelId",cl.code AS "courseLevelCode",cl.name AS "courseLevelName" FROM students s JOIN enrollments e ON e.tenant_id=s.tenant_id AND e.id=$3 JOIN classes c ON c.tenant_id=e.tenant_id AND c.id=e.class_id LEFT JOIN courses co ON co.tenant_id=c.tenant_id AND co.id=c.course_id LEFT JOIN course_levels cl ON cl.tenant_id=c.tenant_id AND cl.id=c.course_level_id WHERE s.tenant_id=$1 AND s.id=$2`,[tenantId,report.studentId,report.enrollmentId]),
      q.query(`SELECT a.id,a.title,a.type,a.assessment_date::text AS "assessmentDate",a.max_score::text AS "maxScore",r.score::text,r.status,r.comment FROM assessments a JOIN assessment_results r ON r.tenant_id=a.tenant_id AND r.assessment_id=a.id AND r.student_id=$2 WHERE a.tenant_id=$1 AND a.class_id=$3 AND a.status='PUBLISHED' AND (a.assessment_date IS NULL OR a.assessment_date BETWEEN $4::date AND $5::date) ORDER BY a.assessment_date,a.id`,[tenantId,report.studentId,report.classId,report.periodStart,report.periodEnd]),
    ]);
    return {version:1,generatedAt:new Date().toISOString(),context:context.rows[0],period:{start:report.periodStart,end:report.periodEnd},narrative:{title:report.title,teacherComment:report.teacherComment,strengths:report.strengths,areasForImprovement:report.areasForImprovement,nextSteps:report.nextSteps},summary,assessments:assessments.rows};
  }
  private validatePeriod(start:string,end:string){if(end<start)throw new BadRequestException('Period end must be on or after period start.');}
  private async enrollment(q:{query:PoolClient['query']},tenantId:string,id:string,studentId:string){const r=await q.query<{classId:string}>(`SELECT class_id AS "classId" FROM enrollments WHERE tenant_id=$1 AND id=$2 AND student_id=$3 AND status<>'TRIAL'`,[tenantId,id,studentId]);if(!r.rows[0])throw new BadRequestException('A non-trial enrollment is required.');return r.rows[0];}
  private async requireClass(q:{query:PoolClient['query']},tenantId:string,id:string){if(!(await q.query('SELECT 1 FROM classes WHERE tenant_id=$1 AND id=$2',[tenantId,id])).rows[0])throw new NotFoundException('Class not found');}
  private async requireStudent(q:{query:PoolClient['query']},tenantId:string,id:string){if(!(await q.query('SELECT 1 FROM students WHERE tenant_id=$1 AND id=$2',[tenantId,id])).rows[0])throw new NotFoundException('Student not found');}
  private async transaction<T>(fn:(client:PoolClient,c:Context)=>Promise<T>){const c=this.tenantContext.get(),client=await c.pool.connect();try{await client.query('BEGIN');const out=await fn(client,c);await client.query('COMMIT');return out;}catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}}
}
