import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { PoolClient, QueryResultRow } from 'pg';
import { ulid } from 'ulid';
import { AuditService } from '../audit/audit.service.js';
import { TenantContextService } from '../tenant/tenant-context.service.js';
import { BranchStatus, type CreateBranchDto } from './dto/create-branch.dto.js';
import type { UpdateBranchDto } from './dto/update-branch.dto.js';

type BranchRow = QueryResultRow & { id:string; tenantId:string; code:string; name:string; address:string|null; phone:string|null; email:string|null; status:BranchStatus; notes:string|null; createdAt:Date; updatedAt:Date; roomCount?:number };
const select = `SELECT b.id, b.tenant_id AS "tenantId", b.code, b.name, b.address, b.phone, b.email, b.status, b.notes, b.created_at AS "createdAt", b.updated_at AS "updatedAt", COUNT(r.id)::int AS "roomCount" FROM branches b LEFT JOIN rooms r ON r.tenant_id = b.tenant_id AND r.branch_id = b.id`;
const snapshot = (row: BranchRow) => ({ code: row.code, name: row.name, address: row.address, phone: row.phone, email: row.email, status: row.status, notes: row.notes });
const serialize = (row: BranchRow) => ({ ...row, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() });
function conflict(error: unknown) { return typeof error === 'object' && error !== null && 'code' in error && error.code === '23505' && 'constraint' in error && error.constraint === 'branches_tenant_id_code_key'; }

@Injectable()
export class BranchesService {
  constructor(private readonly tenantContext: TenantContextService, private readonly audit: AuditService) {}
  async list() { const { tenant, pool } = this.tenantContext.get(); const r = await pool.query<BranchRow>(`${select} WHERE b.tenant_id = $1 GROUP BY b.id ORDER BY b.name, b.id`, [tenant.tenantId]); return r.rows.map(serialize); }
  async get(id:string) { const { tenant, pool } = this.tenantContext.get(); const r = await pool.query<BranchRow>(`${select} WHERE b.tenant_id = $1 AND b.id = $2 GROUP BY b.id`, [tenant.tenantId,id]); if (!r.rows[0]) throw new NotFoundException('Branch not found'); return serialize(r.rows[0]); }
  async create(input:CreateBranchDto) { const context = this.tenantContext.get(); const client = await context.pool.connect(); try { await client.query('BEGIN'); const r = await client.query<BranchRow>(`INSERT INTO branches (id,tenant_id,code,name,address,phone,email,status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,tenant_id AS "tenantId",code,name,address,phone,email,status,notes,created_at AS "createdAt",updated_at AS "updatedAt",0::int AS "roomCount"`, [ulid(),context.tenant.tenantId,input.code.toUpperCase(),input.name,input.address??null,input.phone??null,input.email??null,input.status??BranchStatus.ACTIVE,input.notes??null]); const row=r.rows[0]; await this.audit.recordTenant(client,{ tenantId:context.tenant.tenantId, actorUserId:context.actorUserId, actorMembershipId:context.actorMembershipId, actorName:context.actorName, actorEmail:context.actorEmail, requestId:context.requestId, action:'branch.created', entityType:'BRANCH', entityId:row.id, after:snapshot(row) }); await client.query('COMMIT'); return serialize(row); } catch(e) { await client.query('ROLLBACK').catch(()=>undefined); if(conflict(e)) throw new ConflictException('Branch code already exists'); throw e; } finally { client.release(); } }
  async update(id:string,input:UpdateBranchDto) { const entries: [keyof UpdateBranchDto,string,(v:never)=>unknown][] = [['code','code',(v:string)=>v.toUpperCase()],['name','name',(v:string)=>v],['address','address',(v:string|null)=>v],['phone','phone',(v:string|null)=>v],['email','email',(v:string|null)=>v],['status','status',(v:BranchStatus)=>v],['notes','notes',(v:string|null)=>v]]; const fields:string[]=[]; const values:unknown[]=[]; for(const [p,c,t] of entries) if(Object.hasOwn(input,p)&&input[p]!==undefined){values.push(t(input[p] as never));fields.push(`${c} = $${values.length+2}`);} if(!fields.length) throw new BadRequestException('At least one field is required'); const context=this.tenantContext.get(); const client=await context.pool.connect(); try { await client.query('BEGIN'); const old=await client.query<BranchRow>(`SELECT id, tenant_id AS "tenantId", code, name, address, phone, email, status, notes, created_at AS "createdAt", updated_at AS "updatedAt" FROM branches WHERE tenant_id = $1 AND id = $2 FOR UPDATE`,[context.tenant.tenantId,id]); if(!old.rows[0]) throw new NotFoundException('Branch not found'); const r=await client.query<BranchRow>(`UPDATE branches SET ${fields.join(', ')},updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2 RETURNING id,tenant_id AS "tenantId",code,name,address,phone,email,status,notes,created_at AS "createdAt",updated_at AS "updatedAt",(SELECT COUNT(*)::int FROM rooms r WHERE r.tenant_id = branches.tenant_id AND r.branch_id = branches.id) AS "roomCount"`,[context.tenant.tenantId,id,...values]); const row=r.rows[0]; await this.audit.recordTenant(client,{tenantId:context.tenant.tenantId,actorUserId:context.actorUserId,actorMembershipId:context.actorMembershipId,actorName:context.actorName,actorEmail:context.actorEmail,requestId:context.requestId,action:'branch.updated',entityType:'BRANCH',entityId:id,before:snapshot(old.rows[0]),after:snapshot(row)}); await client.query('COMMIT'); return serialize(row); } catch(e){await client.query('ROLLBACK').catch(()=>undefined);if(conflict(e))throw new ConflictException('Branch code already exists');throw e;}finally{client.release();} }
}
