import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ulid } from 'ulid';
import type { PoolClient } from 'pg';
import { AuditService } from '../audit/audit.service.js';
import { TenantContextService } from '../tenant/tenant-context.service.js';
import type { CreateInvoiceDto } from './dto/create-invoice.dto.js';
import type { CreatePricingPlanDto } from './dto/create-pricing-plan.dto.js';
import type { RecordPaymentDto, ReversePaymentDto } from './dto/record-payment.dto.js';

const money = (value: string | undefined, positive = false) => {
  if (!value || !/^\d+$/.test(value) || (positive ? BigInt(value) <= 0n : BigInt(value) < 0n)) throw new BadRequestException('VND amounts must be integer strings');
  return value;
};
const actor = (context: ReturnType<TenantContextService['get']>) => ({ tenantId: context.tenant.tenantId, actorUserId: context.actorUserId, actorMembershipId: context.actorMembershipId, actorName: context.actorName, actorEmail: context.actorEmail, requestId: context.requestId });
const serialize = (row: Record<string, unknown>) => Object.fromEntries(Object.entries(row).map(([k, v]) => [k, typeof v === 'bigint' ? v.toString() : v instanceof Date ? v.toISOString() : v]));

@Injectable()
export class BillingService {
  constructor(private readonly tenantContext: TenantContextService, private readonly audit: AuditService) {}
  async plans() { const { tenant, pool } = this.tenantContext.get(); return (await pool.query(`SELECT id,tenant_id AS "tenantId",code,name,amount_vnd AS "amountVnd",billing_period AS "billingPeriod",status,created_at AS "createdAt",updated_at AS "updatedAt" FROM pricing_plans WHERE tenant_id=$1 ORDER BY name,id`, [tenant.tenantId])).rows.map(serialize); }
  async createPlan(input: CreatePricingPlanDto) { const c = this.tenantContext.get(); const amount = money(input.amountVnd); try { const r = await c.pool.query(`INSERT INTO pricing_plans (id,tenant_id,code,name,amount_vnd,billing_period) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,tenant_id AS "tenantId",code,name,amount_vnd AS "amountVnd",billing_period AS "billingPeriod",status,created_at AS "createdAt",updated_at AS "updatedAt"`, [ulid(), c.tenant.tenantId, input.code.trim(), input.name.trim(), amount, input.billingPeriod ?? 'ONE_TIME']); return serialize(r.rows[0]); } catch (e) { if (String(e).includes('pricing_plans_tenant_code_key')) throw new ConflictException('Pricing plan code already exists'); throw e; } }
  async invoices(studentId?: string) { const { tenant, pool } = this.tenantContext.get(); const values: unknown[] = [tenant.tenantId]; const filter = studentId ? ' AND i.student_id=$2' : ''; if (studentId) values.push(studentId); const r = await pool.query(`SELECT i.id,i.tenant_id AS "tenantId",i.invoice_number AS "invoiceNumber",i.student_id AS "studentId",i.enrollment_id AS "enrollmentId",i.pricing_plan_id AS "pricingPlanId",i.status,i.issue_date::text AS "issueDate",i.due_date::text AS "dueDate",i.subtotal_vnd AS "subtotalVnd",i.discount_vnd AS "discountVnd",i.total_vnd AS "totalVnd",COALESCE((SELECT SUM(p.amount_vnd) - COALESCE((SELECT SUM(p.amount_vnd) FROM payment_reversals pr JOIN payments p ON p.tenant_id=pr.tenant_id AND p.id=pr.payment_id WHERE pr.tenant_id=i.tenant_id AND p.invoice_id=i.id),0) FROM payments p WHERE p.tenant_id=i.tenant_id AND p.invoice_id=i.id),0) AS "paidVnd" FROM invoices i WHERE i.tenant_id=$1${filter} ORDER BY i.created_at DESC,i.id DESC`, values); return r.rows.map((row) => ({ ...serialize(row), effectiveStatus: effectiveStatus(row.status, row.totalVnd, row.paidVnd) })); }
  async createInvoice(input: CreateInvoiceDto) { const c = this.tenantContext.get(); const discount = BigInt(money(input.discountVnd ?? '0')); if (!Array.isArray(input.items) || input.items.length === 0) throw new BadRequestException('Invoice requires items'); const items = input.items.map((i) => { const q = money(i.quantity, true); const unit = money(i.unitAmountVnd); return { ...i, q, unit, amount: BigInt(q) * BigInt(unit) }; }); const subtotal = items.reduce((x, i) => x + i.amount, 0n); if (discount > subtotal) throw new BadRequestException('Discount exceeds subtotal'); const client = await c.pool.connect(); const id = ulid(); try { await client.query('BEGIN'); await this.requireStudent(client, c.tenant.tenantId, input.studentId); if (input.enrollmentId) await this.requireEnrollment(client, c.tenant.tenantId, input.enrollmentId, input.studentId); await client.query(`INSERT INTO invoices (id,tenant_id,invoice_number,student_id,enrollment_id,pricing_plan_id,status,issue_date,due_date,subtotal_vnd,discount_vnd,total_vnd,notes) VALUES ($1,$2,$3,$4,$5,$6,'DRAFT',$7::date,$8::date,$9,$10,$11,$12)`, [id,c.tenant.tenantId,input.invoiceNumber,input.studentId,input.enrollmentId ?? null,input.pricingPlanId ?? null,input.issueDate ?? null,input.dueDate ?? null,subtotal.toString(),discount.toString(),(subtotal-discount).toString(),input.notes ?? null]); for (const i of items) await client.query(`INSERT INTO invoice_items (id,tenant_id,invoice_id,enrollment_id,description,quantity,unit_amount_vnd,amount_vnd) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`, [ulid(),c.tenant.tenantId,id,i.enrollmentId ?? input.enrollmentId ?? null,i.description,i.q,i.unit,i.amount.toString()]); await this.audit.recordTenant(client, {...actor(c),action:'billing.invoice_created',entityType:'Invoice',entityId:id,after:{studentId:input.studentId,totalVnd:(subtotal-discount).toString()}}); await client.query('COMMIT'); return this.invoice(id); } catch (e) { await client.query('ROLLBACK').catch(()=>undefined); throw e; } finally { client.release(); } }
  async issue(id: string) { return this.command(id, 'ISSUED', 'billing.invoice_issued'); }
  async void(id: string) { return this.command(id, 'VOID', 'billing.invoice_voided'); }
  async recordPayment(invoiceId: string, input: RecordPaymentDto) { const c = this.tenantContext.get(); const amount = money(input.amountVnd, true); const client = await c.pool.connect(); try { await client.query('BEGIN'); const inv = await client.query<{totalVnd:string;status:string}>(`SELECT total_vnd AS "totalVnd",status FROM invoices WHERE tenant_id=$1 AND id=$2 FOR UPDATE`, [c.tenant.tenantId,invoiceId]); if (!inv.rows[0]) throw new NotFoundException('Invoice not found'); if (inv.rows[0].status !== 'ISSUED') throw new ConflictException('Only issued invoices can receive payments'); const paid = await client.query<{sum:string}>(`SELECT COALESCE(SUM(p.amount_vnd) FILTER (WHERE pr.id IS NULL),0)::text AS sum FROM payments p LEFT JOIN payment_reversals pr ON pr.tenant_id=p.tenant_id AND pr.payment_id=p.id WHERE p.tenant_id=$1 AND p.invoice_id=$2`, [c.tenant.tenantId,invoiceId]); if (BigInt(paid.rows[0].sum)+BigInt(amount) > BigInt(inv.rows[0].totalVnd)) throw new ConflictException('Payment exceeds invoice balance'); const id=ulid(); await client.query(`INSERT INTO payments (id,tenant_id,invoice_id,amount_vnd,method,reference,note,received_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,c.tenant.tenantId,invoiceId,amount,input.method,input.reference??null,input.note??null,input.receivedAt??new Date()]); await this.audit.recordTenant(client,{...actor(c),action:'billing.payment_recorded',entityType:'Payment',entityId:id,after:{invoiceId,amountVnd:amount}}); await client.query('COMMIT'); return {id,invoiceId,amountVnd:amount,status:'RECORDED'}; } catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();} }
  async reversePayment(id: string, input: ReversePaymentDto) { const c=this.tenantContext.get(); const client=await c.pool.connect(); try { await client.query('BEGIN'); const r=await client.query<{invoiceId:string;amountVnd:string}>(`SELECT invoice_id AS "invoiceId",amount_vnd AS "amountVnd" FROM payments WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[c.tenant.tenantId,id]); if(!r.rows[0]) throw new NotFoundException('Payment not found'); const existing=await client.query('SELECT 1 FROM payment_reversals WHERE tenant_id=$1 AND payment_id=$2',[c.tenant.tenantId,id]); if(existing.rows[0]) throw new ConflictException('Payment is already reversed'); await client.query(`INSERT INTO payment_reversals (id,tenant_id,payment_id,reason,actor_user_id,actor_membership_id) VALUES ($1,$2,$3,$4,$5,$6)`,[ulid(),c.tenant.tenantId,id,input.reason.trim(),c.actorUserId??null,c.actorMembershipId??null]); await this.audit.recordTenant(client,{...actor(c),action:'billing.payment_reversed',entityType:'Payment',entityId:id,reason:input.reason.trim(),after:{invoiceId:r.rows[0].invoiceId,amountVnd:r.rows[0].amountVnd}}); await client.query('COMMIT'); return {id,status:'REVERSED'}; }catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();} }
  async invoice(id:string){const {tenant,pool}=this.tenantContext.get();const r=await pool.query(`SELECT i.*,COALESCE((SELECT SUM(p.amount_vnd) FILTER (WHERE pr.id IS NULL) FROM payments p LEFT JOIN payment_reversals pr ON pr.tenant_id=p.tenant_id AND pr.payment_id=p.id WHERE p.tenant_id=i.tenant_id AND p.invoice_id=i.id),0) AS paid_vnd FROM invoices i WHERE i.tenant_id=$1 AND i.id=$2`,[tenant.tenantId,id]);if(!r.rows[0])throw new NotFoundException('Invoice not found');return {...serialize(r.rows[0]),effectiveStatus:effectiveStatus(r.rows[0].status,r.rows[0].total_vnd,r.rows[0].paid_vnd)};}
  private async command(id:string,status:string,action:string){const c=this.tenantContext.get();const client=await c.pool.connect();try{await client.query('BEGIN');const r=await client.query(`UPDATE invoices SET status=$3,voided_at=CASE WHEN $3='VOID' THEN CURRENT_TIMESTAMP ELSE voided_at END,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND id=$2 AND status='DRAFT' RETURNING *`,[c.tenant.tenantId,id,status]);if(!r.rows[0])throw new ConflictException('Invoice is not a draft or does not exist');await this.audit.recordTenant(client,{...actor(c),action,entityType:'Invoice',entityId:id,after:{status}});await client.query('COMMIT');return this.invoice(id);}catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();}}
  private async requireStudent(client:PoolClient,tenantId:string,id:string){if(!(await client.query('SELECT 1 FROM students WHERE tenant_id=$1 AND id=$2',[tenantId,id])).rows[0])throw new NotFoundException('Student not found');}
  private async requireEnrollment(client:PoolClient,tenantId:string,id:string,studentId:string){if(!(await client.query('SELECT 1 FROM enrollments WHERE tenant_id=$1 AND id=$2 AND student_id=$3',[tenantId,id,studentId])).rows[0])throw new BadRequestException('Enrollment does not belong to student');}
}
function effectiveStatus(status:string,total:unknown,paid:unknown){if(status==='VOID')return 'VOID';if(BigInt(String(paid??0))>=BigInt(String(total??0)))return 'PAID';if(BigInt(String(paid??0))>0n)return 'PARTIALLY_PAID';return status==='ISSUED'?'OPEN':'DRAFT';}
