import { useQuery } from "@tanstack/react-query";
import { EmptyState } from "@/components/empty-state";
import { getPortalAttendance, getPortalMakeup } from "./api";
import { formatDate, PortalPage, QueryState, StudentSelector, useSelectedStudent } from "./portal-ui";

const labels: Record<string, string> = { PRESENT: "Có mặt", LATE: "Đi muộn", ABSENT_EXCUSED: "Vắng có phép", ABSENT_UNEXCUSED: "Vắng không phép", ONLINE: "Trực tuyến", MAKEUP: "Học bù" };

export function PortalAttendancePage() {
  const { me, student, select } = useSelectedStudent();
  const attendance = useQuery({ queryKey: ["portal", "attendance", student?.id], queryFn: () => getPortalAttendance(student!.id), enabled: Boolean(student) });
  const makeup = useQuery({ queryKey: ["portal", "makeup", student?.id], queryFn: () => getPortalMakeup(student!.id), enabled: Boolean(student) });
  return <PortalPage title="Điểm danh & học bù" description="Chỉ hiển thị kết quả điểm danh đã được trung tâm chốt."><StudentSelector student={student} students={me.data?.students ?? []} onChange={select} /><QueryState query={attendance}>{attendance.data && <><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Đã tham gia", attendance.data.summary.attended], ["Vắng", attendance.data.summary.absent], ["Đi muộn", attendance.data.summary.late], ["Tỷ lệ", attendance.data.summary.percentage == null ? "—" : `${attendance.data.summary.percentage}%`]].map(([label, value]) => <div key={label} className="rounded-xl border border-[#e2e8f0] bg-white p-4"><strong className="block text-xl text-[#0f172a]">{value}</strong><span className="text-sm text-[#64748b]">{label}</span></div>)}</div>{attendance.data.data.length ? <div className="register"><table><thead><tr><th>Ngày</th><th>Lớp</th><th>Thời gian</th><th>Kết quả</th></tr></thead><tbody>{attendance.data.data.map((item) => <tr key={`${item.date}-${item.startTime}-${item.className}`}><td data-label="Ngày">{formatDate(item.date)}</td><td data-label="Lớp" className="font-semibold">{item.className}</td><td data-label="Thời gian">{item.startTime}–{item.endTime}</td><td data-label="Kết quả"><span className={`status ${item.status.startsWith("ABSENT") ? "disabled" : ""}`}>{labels[item.status] ?? item.status}</span></td></tr>)}</tbody></table></div> : <EmptyState title="Chưa có kết quả điểm danh" />}</>}</QueryState><section className="mt-8"><h2>Quyền học bù</h2><div className="mt-4"><QueryState query={makeup}>{makeup.data?.length ? <div className="grid gap-3">{makeup.data.map((item) => <article key={`${item.sourceDate}-${item.sourceClassName}-${item.expiresAt}`} className="rounded-xl border border-[#e2e8f0] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="m-0 font-semibold">{item.sourceClassName} · {formatDate(item.sourceDate)}</p><span className={`status ${item.status === "EXPIRED" ? "disabled" : ""}`}>{item.status}</span></div><p className="mt-2 text-sm text-[#64748b]">Hết hạn {formatDate(item.expiresAt)}{item.destinationDate ? ` · Đã xếp ${item.destinationClassName} vào ${formatDate(item.destinationDate)} ${item.destinationStartTime}` : ""}</p></article>)}</div> : <EmptyState title="Không có quyền học bù" />}</QueryState></div></section></PortalPage>;
}
