import { useQuery } from "@tanstack/react-query";
import { Navigate } from "react-router-dom";
import { EmptyState } from "@/components/empty-state";
import { getPortalBilling } from "./api";
import { formatDate, formatDateTime, formatMoney, PortalPage, QueryState, StudentSelector, useSelectedStudent } from "./portal-ui";

export function PortalBillingPage() {
  const { me, student, select } = useSelectedStudent();
  const query = useQuery({ queryKey: ["portal", "billing", student?.id], queryFn: () => getPortalBilling(student!.id), enabled: Boolean(student?.canViewBilling), retry: false });
  if (student && !student.canViewBilling) return <Navigate to="/portal" replace />;
  return <PortalPage title="Học phí" description="Hóa đơn và khoản thu đã ghi nhận cho học viên mà bạn là liên hệ thanh toán."><StudentSelector student={student} students={me.data?.students.filter((item) => item.canViewBilling) ?? []} onChange={select} /><QueryState query={query}>{query.data && <div className="grid gap-8"><section><h2>Hóa đơn</h2><div className="mt-4 grid gap-3">{query.data.invoices.length ? query.data.invoices.map((invoice) => <article key={invoice.invoiceNumber} className="rounded-xl border border-[#e2e8f0] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="m-0 text-base font-semibold">{invoice.invoiceNumber}</h3><p className="mt-1 text-sm text-[#64748b]">Phát hành {formatDate(invoice.issueDate)} · Hạn {formatDate(invoice.dueDate)}</p></div><span className={`status ${invoice.effectiveStatus === "OVERDUE" || invoice.effectiveStatus === "VOID" ? "disabled" : ""}`}>{invoice.effectiveStatus}</span></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#f1f5f9] pt-4 sm:grid-cols-4"><p className="m-0"><span className="block text-xs text-[#64748b]">Tổng</span><strong>{formatMoney(invoice.totalVnd)}</strong></p><p className="m-0"><span className="block text-xs text-[#64748b]">Điều chỉnh</span><strong>{formatMoney(invoice.creditVnd)}</strong></p><p className="m-0"><span className="block text-xs text-[#64748b]">Đã thanh toán</span><strong>{formatMoney(invoice.paidVnd)}</strong></p><p className="m-0"><span className="block text-xs text-[#64748b]">Còn lại</span><strong>{formatMoney(invoice.outstandingVnd)}</strong></p></div>{invoice.items.length > 0 && <ul className="mt-4 mb-0 grid gap-2 pl-5 text-sm text-[#475569]">{invoice.items.map((item, index) => <li key={`${item.description}-${index}`}>{item.description}: {formatMoney(item.amountVnd)}</li>)}</ul>}</article>) : <EmptyState title="Chưa có hóa đơn" />}</div></section><section><h2>Thanh toán & hoàn tiền</h2><div className="mt-4 overflow-hidden rounded-xl border border-[#e2e8f0] bg-white">{query.data.payments.map((payment) => <div key={`${payment.receivedAt}-${payment.amountVnd}-${payment.method}`} className="flex flex-wrap justify-between gap-2 border-b border-[#f1f5f9] p-4 last:border-0"><span>{formatDateTime(payment.receivedAt)} · {payment.method}</span><strong>{formatMoney(payment.amountVnd)}</strong></div>)}{query.data.refunds.map((refund) => <div key={`${refund.refundedAt}-${refund.amountVnd}`} className="flex flex-wrap justify-between gap-2 border-b border-[#f1f5f9] p-4 last:border-0"><span>{formatDateTime(refund.refundedAt)} · Hoàn tiền</span><strong>−{formatMoney(refund.amountVnd)}</strong></div>)}{!query.data.payments.length && !query.data.refunds.length && <p className="m-0 p-5 text-sm text-[#64748b]">Chưa có giao dịch.</p>}</div></section></div>}</QueryState></PortalPage>;
}
