-- LOCAL-08 financial completeness ledger.
CREATE TABLE discounts (id CHAR(26) PRIMARY KEY, tenant_id CHAR(26) NOT NULL, code TEXT NOT NULL, name TEXT NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('PERCENTAGE','FIXED')), value BIGINT NOT NULL CHECK (value >= 0), max_amount_vnd BIGINT, status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')), effective_from DATE, effective_until DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT discounts_tenant_id_key UNIQUE (tenant_id,id), CONSTRAINT discounts_tenant_code_key UNIQUE (tenant_id,code), CONSTRAINT discounts_percentage_check CHECK (kind <> 'PERCENTAGE' OR value <= 100), CONSTRAINT discounts_dates_check CHECK (effective_until IS NULL OR effective_from IS NULL OR effective_until >= effective_from));
CREATE INDEX discounts_tenant_status_idx ON discounts (tenant_id,status,effective_from,id);
CREATE TABLE enrollment_pricing (id CHAR(26) PRIMARY KEY, tenant_id CHAR(26) NOT NULL, enrollment_id CHAR(26) NOT NULL, pricing_plan_id CHAR(26), amount_vnd BIGINT NOT NULL CHECK (amount_vnd >= 0), currency TEXT NOT NULL DEFAULT 'VND' CHECK (currency = 'VND'), effective_from DATE NOT NULL, effective_until DATE, locked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT enrollment_pricing_tenant_id_key UNIQUE (tenant_id,id), CONSTRAINT enrollment_pricing_dates_check CHECK (effective_until IS NULL OR effective_until >= effective_from), CONSTRAINT enrollment_pricing_enrollment_fkey FOREIGN KEY (tenant_id,enrollment_id) REFERENCES enrollments(tenant_id,id), CONSTRAINT enrollment_pricing_plan_fkey FOREIGN KEY (tenant_id,pricing_plan_id) REFERENCES pricing_plans(tenant_id,id));
CREATE INDEX enrollment_pricing_lookup_idx ON enrollment_pricing (tenant_id,enrollment_id,effective_from DESC,id DESC);
CREATE UNIQUE INDEX enrollment_pricing_one_active_idx ON enrollment_pricing (tenant_id,enrollment_id) WHERE effective_until IS NULL;
CREATE TABLE enrollment_discounts (id CHAR(26) PRIMARY KEY, tenant_id CHAR(26) NOT NULL, enrollment_id CHAR(26) NOT NULL, discount_id CHAR(26) NOT NULL, amount_vnd BIGINT NOT NULL CHECK (amount_vnd >= 0), applied_at DATE NOT NULL DEFAULT CURRENT_DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT enrollment_discounts_tenant_id_key UNIQUE (tenant_id,id), CONSTRAINT enrollment_discounts_enrollment_fkey FOREIGN KEY (tenant_id,enrollment_id) REFERENCES enrollments(tenant_id,id), CONSTRAINT enrollment_discounts_discount_fkey FOREIGN KEY (tenant_id,discount_id) REFERENCES discounts(tenant_id,id), CONSTRAINT enrollment_discounts_unique_key UNIQUE (tenant_id,enrollment_id,discount_id));
CREATE TABLE invoice_status_history (id CHAR(26) PRIMARY KEY, tenant_id CHAR(26) NOT NULL, invoice_id CHAR(26) NOT NULL, status TEXT NOT NULL CHECK (status IN ('DRAFT','ISSUED','VOID')), effective_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT invoice_status_history_tenant_id_key UNIQUE (tenant_id,id), CONSTRAINT invoice_status_history_invoice_fkey FOREIGN KEY (tenant_id,invoice_id) REFERENCES invoices(tenant_id,id));
CREATE INDEX invoice_status_history_lookup_idx ON invoice_status_history (tenant_id,invoice_id,effective_at DESC,status,id DESC);
CREATE TABLE credit_notes (id CHAR(26) PRIMARY KEY, tenant_id CHAR(26) NOT NULL, credit_note_number TEXT NOT NULL, invoice_id CHAR(26) NOT NULL, amount_vnd BIGINT NOT NULL CHECK (amount_vnd > 0), reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ISSUED' CHECK (status IN ('DRAFT','ISSUED','VOID')), issued_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT credit_notes_tenant_id_key UNIQUE (tenant_id,id), CONSTRAINT credit_notes_tenant_number_key UNIQUE (tenant_id,credit_note_number), CONSTRAINT credit_notes_invoice_fkey FOREIGN KEY (tenant_id,invoice_id) REFERENCES invoices(tenant_id,id));
CREATE INDEX credit_notes_invoice_idx ON credit_notes (tenant_id,invoice_id,status,id);
ALTER TABLE payments ALTER COLUMN invoice_id DROP NOT NULL;
CREATE TABLE payment_allocations (id CHAR(26) PRIMARY KEY, tenant_id CHAR(26) NOT NULL, payment_id CHAR(26) NOT NULL, invoice_id CHAR(26) NOT NULL, amount_vnd BIGINT NOT NULL CHECK (amount_vnd > 0), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT payment_allocations_tenant_id_key UNIQUE (tenant_id,id), CONSTRAINT payment_allocations_payment_fkey FOREIGN KEY (tenant_id,payment_id) REFERENCES payments(tenant_id,id), CONSTRAINT payment_allocations_invoice_fkey FOREIGN KEY (tenant_id,invoice_id) REFERENCES invoices(tenant_id,id), CONSTRAINT payment_allocations_unique_key UNIQUE (tenant_id,payment_id,invoice_id));
CREATE INDEX payment_allocations_invoice_idx ON payment_allocations (tenant_id,invoice_id,created_at,id);

-- Preserve historical invoice-linked payments in the allocation ledger before all
-- financial reads switch to payment_allocations as their source of truth.
INSERT INTO payment_allocations (id, tenant_id, payment_id, invoice_id, amount_vnd, created_at)
SELECT substr(md5(p.tenant_id || ':payment:' || p.id || ':' || p.invoice_id), 1, 26),
       p.tenant_id, p.id, p.invoice_id, p.amount_vnd, p.created_at
FROM payments p
WHERE p.invoice_id IS NOT NULL
ON CONFLICT (tenant_id, payment_id, invoice_id) DO NOTHING;

CREATE TABLE refunds (id CHAR(26) PRIMARY KEY, tenant_id CHAR(26) NOT NULL, payment_id CHAR(26) NOT NULL, amount_vnd BIGINT NOT NULL CHECK (amount_vnd > 0), reason TEXT NOT NULL, actor_user_id CHAR(26), actor_membership_id CHAR(26), idempotency_key TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT refunds_tenant_id_key UNIQUE (tenant_id,id), CONSTRAINT refunds_payment_key UNIQUE (tenant_id,payment_id,idempotency_key), CONSTRAINT refunds_payment_fkey FOREIGN KEY (tenant_id,payment_id) REFERENCES payments(tenant_id,id));
CREATE INDEX refunds_payment_idx ON refunds (tenant_id,payment_id,created_at,id);
