import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, ArrowRight, CalendarDays, ClipboardCheck, CreditCard, GraduationCap, HandCoins, Megaphone, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState } from "@/components/empty-state";
import { ErrorState } from "@/components/error-state";
import { LoadingState } from "@/components/loading-state";
import { PageContainer } from "@/components/page-container";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { getApiErrorMessage } from "@/lib/api";
import { dashboardQueryKey, getDashboard } from "./api";
import type { DashboardAttention, DashboardResponse, DashboardStatus } from "./types";

const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("vi-VN");
const statusLabels: Record<string, string> = { SCHEDULED: "Đã lên lịch", COMPLETED: "Đã hoàn tất", CANCELLED: "Đã hủy", RESCHEDULED: "Đổi lịch", BOOKED: "Đã đặt học thử", NEW: "Mới", CONTACTED: "Đã liên hệ", QUALIFIED: "Đủ điều kiện", TRIAL_BOOKED: "Đã đặt học thử", TRIAL_COMPLETED: "Đã học thử" };
const severityLabels: Record<string, string> = { HIGH: "Cần xử lý", MEDIUM: "Lưu ý", LOW: "Thông tin" };

function formatNumber(value: number | string | undefined) { return value === undefined ? "—" : number.format(Number(value)); }
function formatMoney(value: number | string | undefined) { return value === undefined ? "—" : money.format(Number(value)); }
function formatDate(value: string | undefined) { return value ? new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit" }).format(new Date(`${value}${value.length === 10 ? "T00:00:00" : ""}`)) : "—"; }
function formatDateTime(value: string | undefined) { return value ? new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—"; }
function label(status: DashboardStatus | undefined) { return status ? statusLabels[status] ?? status : "—"; }
function safeHref(href: string | undefined) { return href && href.startsWith("/") ? href : undefined; }

function SectionCard({ title, icon: Icon, children }: { title: string; icon: typeof CalendarDays; children: React.ReactNode }) {
  return <section className="min-w-0 rounded-xl border border-[#e2e8f0] bg-white shadow-[0_1px_2px_rgba(15,23,42,.04)]"><div className="flex items-center gap-2 border-b border-[#f1f5f9] px-5 py-4"><Icon size={18} className="text-[#2563eb]" aria-hidden="true" /><h2 className="text-base font-semibold text-[#0f172a]">{title}</h2></div>{children}</section>;
}

function Metric({ label: title, value, tone = "blue" }: { label: string; value: React.ReactNode; tone?: "blue" | "amber" | "red" | "green" }) {
  const colors = { blue: "bg-[#eff6ff] text-[#2563eb]", amber: "bg-[#fff7ed] text-[#c2410c]", red: "bg-[#fef2f2] text-[#b42318]", green: "bg-[#ecfdf5] text-[#047857]" };
  return <div className="min-w-0 rounded-lg border border-[#edf0f5] p-4"><p className="m-0 truncate text-xs font-medium text-[#64748b]">{title}</p><p className={`mt-2 inline-flex max-w-full rounded-md px-2.5 py-1 text-xl font-bold tabular-nums ${colors[tone]}`}>{value}</p></div>;
}

function CompactRow({ label: title, value, href, tone }: { label: string; value: React.ReactNode; href?: string; tone?: "red" | "green" }) {
  const content = <><span className="text-sm text-[#64748b]">{title}</span><span className={`text-sm font-semibold tabular-nums ${tone === "red" ? "text-[#b42318]" : tone === "green" ? "text-[#047857]" : "text-[#0f172a]"}`}>{value}</span></>;
  return href ? <Link to={href} className="flex min-h-10 items-center justify-between gap-3 border-b border-[#f1f5f9] px-1 last:border-0 hover:bg-[#f8fafc]">{content}<ArrowRight size={15} className="shrink-0 text-[#94a3b8]" aria-hidden="true" /></Link> : <div className="flex min-h-10 items-center justify-between gap-3 border-b border-[#f1f5f9] last:border-0">{content}</div>;
}

function AttentionList({ items }: { items: DashboardAttention[] }) {
  return <SectionCard title="Cần chú ý" icon={AlertTriangle}><div className="divide-y divide-[#f1f5f9]">{items.slice(0, 8).map((item, index) => { const href = safeHref(item.href); const content = <div className="flex gap-3 px-5 py-4"><span className={`mt-1 size-2 shrink-0 rounded-full ${item.severity === "HIGH" ? "bg-[#dc2626]" : item.severity === "MEDIUM" ? "bg-[#f59e0b]" : "bg-[#94a3b8]"}`} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="m-0 text-sm font-semibold text-[#0f172a]">{item.title}</p><span className="text-[11px] font-semibold text-[#64748b]">{severityLabels[item.severity] ?? item.severity}</span></div>{item.description && <p className="mt-1 mb-0 text-sm leading-5 text-[#64748b]">{item.description}</p>}{item.date && <p className="mt-1 mb-0 text-xs text-[#94a3b8]">{formatDate(item.date)}</p>}</div></div>; return href ? <Link key={`${item.type}-${index}`} to={href} className="block hover:bg-[#f8fafc]">{content}</Link> : <div key={`${item.type}-${index}`}>{content}</div>; })}</div></SectionCard>;
}

function AcademicSection({ section }: { section: NonNullable<DashboardResponse["sections"]["academic"]> }) {
  const sessions = section.sessionsToday ?? {};
  return <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(360px,.9fr)]"><SectionCard title="Học tập hôm nay" icon={GraduationCap}><div className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-4">{section.activeStudentCount !== undefined && <Metric label="Học viên đang học" value={formatNumber(section.activeStudentCount)} />}{section.activeClassCount !== undefined && <Metric label="Lớp đang hoạt động" value={formatNumber(section.activeClassCount)} />}{sessions.total !== undefined && <Metric label="Buổi hôm nay" value={formatNumber(sessions.total)} tone="green" />}{sessions.completed !== undefined && <Metric label="Đã hoàn tất" value={formatNumber(sessions.completed)} tone="green" />}</div><div className="px-5 pb-4">{section.pendingAttendanceCount !== undefined && <CompactRow label="Chờ điểm danh" value={formatNumber(section.pendingAttendanceCount)} href="/schedule" tone="red" />}{section.availableMakeupCount !== undefined && <CompactRow label="Lớp bù khả dụng" value={formatNumber(section.availableMakeupCount)} href="/schedule" />}{section.draftAssessmentCount !== undefined && <CompactRow label="Bài đánh giá nháp" value={formatNumber(section.draftAssessmentCount)} href="/classes" />}{section.draftProgressReportCount !== undefined && <CompactRow label="Báo cáo tiến độ nháp" value={formatNumber(section.draftProgressReportCount)} href="/classes" />}</div></SectionCard><SectionCard title="Buổi học sắp tới" icon={CalendarDays}>{section.upcomingSessions?.length ? <div className="divide-y divide-[#f1f5f9]">{section.upcomingSessions.slice(0, 6).map((session) => <Link key={session.id} to={session.status === "SCHEDULED" ? `/attendance-sessions/${session.id}` : "/schedule"} className="flex min-w-0 items-start gap-3 px-5 py-3 hover:bg-[#f8fafc]"><div className="w-16 shrink-0"><p className="m-0 text-sm font-bold text-[#0f172a]">{session.startTime}</p><p className="mt-0.5 mb-0 text-xs text-[#64748b]">{formatDate(session.date)}</p></div><div className="min-w-0 flex-1"><p className="m-0 truncate text-sm font-semibold text-[#0f172a]">{session.className ?? "Lớp học"}</p><p className="mt-1 truncate text-xs text-[#64748b]">{[session.teacherName, session.roomName, session.branchName].filter(Boolean).join(" · ") || "Chưa có thông tin bổ sung"}</p></div><StatusBadge status={(session.status as "SCHEDULED")}>{label(session.status)}</StatusBadge></Link>)}</div> : <p className="m-0 px-5 py-8 text-sm text-[#64748b]">Không có buổi học sắp tới.</p>}</SectionCard></div>;
}

function FinanceSection({ section }: { section: NonNullable<DashboardResponse["sections"]["finance"]> }) {
  const billing = section.billing ?? {};
  return <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(360px,.9fr)]"><SectionCard title="Tài chính" icon={CreditCard}><div className="grid grid-cols-1 gap-3 p-5 sm:grid-cols-3">{billing.outstandingVnd !== undefined && <Metric label="Công nợ hiện tại" value={formatMoney(billing.outstandingVnd)} tone="amber" />}{billing.overdueVnd !== undefined && <Metric label="Công nợ quá hạn" value={formatMoney(billing.overdueVnd)} tone="red" />}{billing.collectedThisMonthVnd !== undefined && <Metric label="Thu trong tháng" value={formatMoney(billing.collectedThisMonthVnd)} tone="green" />}</div>{section.compensation && <div className="px-5 pb-4">{section.compensation.draftPeriodCount !== undefined && <CompactRow label="Kỳ lương nháp" value={formatNumber(section.compensation.draftPeriodCount)} href="/billing/compensation" />}{section.compensation.unresolvedIssueCount !== undefined && <CompactRow label="Vấn đề chưa xử lý" value={formatNumber(section.compensation.unresolvedIssueCount)} href="/billing/compensation" tone="red" />}{section.compensation.latestFinalizedPayableVnd !== undefined && <CompactRow label="Khoản phải trả đã chốt gần nhất" value={formatMoney(section.compensation.latestFinalizedPayableVnd)} href="/billing/compensation" />}</div>}</SectionCard><SectionCard title="Công nợ quá hạn" icon={HandCoins}>{section.overdueReceivables?.length ? <div className="divide-y divide-[#f1f5f9]">{section.overdueReceivables.slice(0, 5).map((item) => <Link key={item.invoiceId} to="/billing/receivables" className="flex min-w-0 items-center gap-3 px-5 py-3 hover:bg-[#f8fafc]"><div className="min-w-0 flex-1"><p className="m-0 truncate text-sm font-semibold text-[#0f172a]">{item.studentName ?? item.invoiceNumber ?? "Hóa đơn"}</p><p className="mt-1 mb-0 text-xs text-[#64748b]">{item.invoiceNumber ?? ""} · quá hạn {item.daysOverdue} ngày</p></div><span className="shrink-0 text-sm font-semibold text-[#b42318]">{formatMoney(item.outstandingVnd)}</span></Link>)}</div> : <p className="m-0 px-5 py-8 text-sm text-[#64748b]">Không có công nợ quá hạn.</p>}</SectionCard></div>;
}

function GrowthSection({ section }: { section: NonNullable<DashboardResponse["sections"]["growth"]> }) {
  const pipeline = section.pipeline ?? {};
  return <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(360px,.9fr)]"><SectionCard title="Tăng trưởng" icon={UsersRound}><div className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-4">{section.activeLeadCount !== undefined && <Metric label="Tiềm năng đang hoạt động" value={formatNumber(section.activeLeadCount)} />}{section.followUpsTodayCount !== undefined && <Metric label="Theo dõi hôm nay" value={formatNumber(section.followUpsTodayCount)} />}{section.overdueFollowUpCount !== undefined && <Metric label="Theo dõi quá hạn" value={formatNumber(section.overdueFollowUpCount)} tone="red" />}{section.upcomingTrialCount !== undefined && <Metric label="Học thử sắp tới" value={formatNumber(section.upcomingTrialCount)} tone="amber" />}</div><div className="px-5 pb-4">{pipeline.NEW !== undefined && <CompactRow label="Mới" value={formatNumber(pipeline.NEW)} href="/leads" />}{pipeline.CONTACTED !== undefined && <CompactRow label="Đã liên hệ" value={formatNumber(pipeline.CONTACTED)} href="/leads" />}{pipeline.QUALIFIED !== undefined && <CompactRow label="Đủ điều kiện" value={formatNumber(pipeline.QUALIFIED)} href="/leads" />}{section.wonThisMonthCount !== undefined && <CompactRow label="Thắng trong tháng" value={formatNumber(section.wonThisMonthCount)} href="/leads" tone="green" />}</div></SectionCard><SectionCard title="Theo dõi & học thử" icon={ClipboardCheck}>{section.followUps?.length || section.trials?.length ? <div className="divide-y divide-[#f1f5f9]">{(section.followUps ?? []).slice(0, 3).map((followUp) => <Link key={followUp.leadId} to={`/leads/${followUp.leadId}`} className="flex min-w-0 items-center gap-3 px-5 py-3 hover:bg-[#f8fafc]"><div className="min-w-0 flex-1"><p className="m-0 truncate text-sm font-semibold text-[#0f172a]">{followUp.studentName ?? "Tiềm năng"}</p><p className="mt-1 mb-0 truncate text-xs text-[#64748b]">{followUp.assigneeName ?? "Chưa phân công"} · {formatDateTime(followUp.nextFollowUpAt)}</p></div><StatusBadge status={(followUp.status === "NEW" ? "PENDING" : "ACTIVE")}>{label(followUp.status)}</StatusBadge></Link>)}{(section.trials ?? []).slice(0, 3).map((trial) => <Link key={trial.id} to={trial.leadId ? `/leads/${trial.leadId}` : "/leads"} className="flex min-w-0 items-center gap-3 px-5 py-3 hover:bg-[#f8fafc]"><div className="min-w-0 flex-1"><p className="m-0 truncate text-sm font-semibold text-[#0f172a]">{trial.leadName ?? "Học thử"}</p><p className="mt-1 mb-0 truncate text-xs text-[#64748b]">{formatDate(trial.sessionDate)}{trial.startTime ? ` · ${trial.startTime}` : ""} · {trial.className ?? "Chưa xếp lớp"}</p></div><StatusBadge status={(trial.status as "BOOKED")}>{label(trial.status)}</StatusBadge></Link>)}</div> : <p className="m-0 px-5 py-8 text-sm text-[#64748b]">Không có việc theo dõi hoặc học thử sắp tới.</p>}</SectionCard></div>;
}

export function DashboardPage() {
  const dashboard = useQuery({ queryKey: dashboardQueryKey(), queryFn: getDashboard, refetchInterval: 60_000 });
  if (dashboard.isPending) return <PageContainer><PageHeader title="Tổng quan" description="Tình hình vận hành hôm nay." /><LoadingState label="Đang tải tổng quan" /></PageContainer>;
  if (dashboard.isError) return <PageContainer><PageHeader title="Tổng quan" description="Tình hình vận hành hôm nay." /><ErrorState title="Không thể tải tổng quan" message={getApiErrorMessage(dashboard.error, "Kiểm tra kết nối và thử lại.")} onRetry={() => void dashboard.refetch()} /></PageContainer>;
  const data = dashboard.data;
  const { academic, finance, growth, attention = [] } = data.sections;
  const hasSections = Boolean(academic || finance || growth || attention.length);
  return <PageContainer><PageHeader title="Tổng quan" description={`Tình hình vận hành ngày ${formatDate(data.businessDate)}.`} /><div className="grid gap-5">{attention.length > 0 && <AttentionList items={attention} />}{academic && <AcademicSection section={academic} />}{finance && <FinanceSection section={finance} />}{growth && <GrowthSection section={growth} />}{!hasSections && <EmptyState icon={Megaphone} title="Chưa có dữ liệu tổng quan" description="Các chỉ số vận hành sẽ xuất hiện khi trung tâm có dữ liệu phù hợp." />}</div></PageContainer>;
}
