import dotenv from 'dotenv'; dotenv.config({override:true});
import { escapeIdentifier, Pool } from 'pg';
import { ulid } from 'ulid';
import { afterAll,beforeAll,describe,expect,it,vi } from 'vitest';
import { BadRequestException,ConflictException,NotFoundException } from '@nestjs/common';
import { postgresConfig } from '../src/config.js';
import { deployTenantSchema } from '../src/database/tenant-migrations.js';
import { TenantContextService,type TenantContext } from '../src/tenant/tenant-context.service.js';
import { ProgressService } from '../src/progress/progress.service.js';
import { PortalProgressController } from '../src/progress/portal-progress.controller.js';
import { AssessmentType,ScoringMode } from '../src/progress/dto/assessment.dto.js';
import { ResultStatus } from '../src/progress/dto/result.dto.js';

const enabled=process.env.B5_TEST_DATABASE==='1';
describe.skipIf(!enabled)('LOCAL-13 progress hard gates (real PostgreSQL)',()=>{
 let admin:Pool,a:Pool,b:Pool,context:TenantContextService,service:ProgressService,portal:PortalProgressController; const names={a:'',b:''};
 const ids={ta:ulid(),tb:ulid(),student:ulid(),other:ulid(),cross:ulid(),klass:ulid(),otherClass:ulid(),enrollment:ulid(),trial:ulid(),owner:ulid()};
 const meta={tenantId:ids.ta,tenantSlug:'progress-a',dbName:''};
 const run=<T>(fn:()=>Promise<T>)=>context.run<T>({tenant:meta,pool:a,actorUserId:ids.owner,actorMembershipId:ulid(),actorName:'Owner'} as TenantContext,fn);
 beforeAll(async()=>{const c=postgresConfig(),runId=`${Date.now()}_${process.pid}`;names.a=`classora_local13_${runId}_a`;names.b=`classora_local13_${runId}_b`;meta.dbName=names.a;admin=new Pool({host:c.host,port:c.port,user:c.user,password:c.password,database:c.controlDatabase});for(const n of Object.values(names))await admin.query(`CREATE DATABASE ${escapeIdentifier(n)}`);await deployTenantSchema(names.a);await deployTenantSchema(names.b);const base={host:c.host,port:c.port,user:c.user,password:c.password};a=new Pool({...base,database:names.a,max:12});b=new Pool({...base,database:names.b,max:4});await a.query(`INSERT INTO students(id,tenant_id,code,full_name) VALUES($1,$2,'S1','Student'),($3,$2,'S2','Other')`,[ids.student,ids.ta,ids.other]);await a.query(`INSERT INTO classes(id,tenant_id,code,name) VALUES($1,$2,'C1','Class'),($3,$2,'C2','Other class')`,[ids.klass,ids.ta,ids.otherClass]);await a.query(`INSERT INTO enrollments(id,tenant_id,student_id,class_id,status) VALUES($1,$2,$3,$4,'ACTIVE'),($5,$2,$6,$4,'TRIAL')`,[ids.enrollment,ids.ta,ids.student,ids.klass,ids.trial,ids.other]);await b.query(`INSERT INTO students(id,tenant_id,code,full_name) VALUES($1,$2,'X','Cross')`,[ids.cross,ids.tb]);context=new TenantContextService();const audit={recordTenant:vi.fn().mockResolvedValue(undefined)};service=new ProgressService(context,audit as never);portal=new PortalProgressController(context);},120000);
 afterAll(async()=>{for(const p of [a,b,admin])await p?.end().catch(()=>undefined);const c=postgresConfig(),cleanup=new Pool({host:c.host,port:c.port,user:c.user,password:c.password,database:c.controlDatabase});for(const n of Object.values(names))await cleanup.query(`DROP DATABASE IF EXISTS ${escapeIdentifier(n)} WITH (FORCE)`).catch(()=>undefined);await cleanup.end();});
 it('grades SIMPLE exactly and excludes TRIAL and wrong-class enrollments',async()=>{const assessment=await run(()=>service.createAssessment(ids.klass,{type:AssessmentType.QUIZ,title:'Simple',scoringMode:ScoringMode.SIMPLE,maxScore:'10.00'}));await run(()=>service.saveResults(assessment.id,{results:[{studentId:ids.student,status:ResultStatus.GRADED,score:'8.50'}]}));expect((await run(()=>service.getAssessment(assessment.id))).results[0].score).toBe('8.50');await expect(run(()=>service.saveResults(assessment.id,{results:[{studentId:ids.other,status:ResultStatus.GRADED,score:'5.00'}]}))).rejects.toBeInstanceOf(BadRequestException);await expect(a.query(`INSERT INTO assessment_results(id,tenant_id,assessment_id,student_id,enrollment_id,score,status) VALUES($1,$2,$3,$4,$5,1,'GRADED')`,[ulid(),ids.ta,assessment.id,ids.other,ids.trial])).rejects.toThrow();});
 it('derives complete RUBRIC totals and enforces criterion graph in PostgreSQL',async()=>{const assessment=await run(()=>service.createAssessment(ids.klass,{type:AssessmentType.PROJECT,title:'Rubric',scoringMode:ScoringMode.RUBRIC,maxScore:'5.00',criteria:[{name:'A',maxScore:'2.00'},{name:'B',maxScore:'3.00'}]}));await run(()=>service.saveResults(assessment.id,{results:[{studentId:ids.student,status:ResultStatus.GRADED,criterionScores:assessment.criteria.map((c:{id:string},i:number)=>({criterionId:c.id,score:i?'2.50':'1.50'}))}]}));expect((await run(()=>service.getAssessment(assessment.id))).results[0].score).toBe('4.00');await expect(a.query(`UPDATE assessment_criterion_results SET score=999 WHERE tenant_id=$1`,[ids.ta])).rejects.toThrow();});
 it('serializes publish against draft gradebook writes',async()=>{const assessment=await run(()=>service.createAssessment(ids.klass,{type:AssessmentType.TEST,title:'Race',scoringMode:ScoringMode.SIMPLE,maxScore:'10.00'}));const results=await Promise.allSettled([run(()=>service.publishAssessment(assessment.id)),run(()=>service.saveResults(assessment.id,{results:[{studentId:ids.student,status:ResultStatus.GRADED,score:'7.00'}]}))]);expect(results.filter(x=>x.status==='fulfilled').length).toBeGreaterThanOrEqual(1);const final=await run(()=>service.getAssessment(assessment.id));expect(final.status).toBe('PUBLISHED');if(results.every(x=>x.status==='fulfilled'))expect(final.results[0].score).toBe('7.00');});
 it('appends serialized published corrections with server snapshots',async()=>{const assessment=await run(()=>service.createAssessment(ids.klass,{type:AssessmentType.EXAM,title:'Correction',scoringMode:ScoringMode.SIMPLE,maxScore:'10.00'}));await run(()=>service.saveResults(assessment.id,{results:[{studentId:ids.student,status:ResultStatus.GRADED,score:'5.00'}]}));await run(()=>service.publishAssessment(assessment.id));const result=(await run(()=>service.getAssessment(assessment.id))).results[0];await Promise.all([run(()=>service.correctResult(result.id,{reason:'first',score:'6.00'})),run(()=>service.correctResult(result.id,{reason:'second',score:'7.00'}))]);const history=await run(()=>service.resultHistory(result.id));expect(history).toHaveLength(2);for(let i=1;i<history.length;i++)expect(history[i].beforeSnapshot.score).toBe(history[i-1].afterSnapshot.score);expect(new Set(history.map((item:any)=>item.afterSnapshot.score))).toEqual(new Set(['6.00','7.00']));});
 it('keeps notes append-only/private and publishes immutable report snapshots with one replacement',async()=>{const note=await run(()=>service.createNote(ids.student,{content:'private'}));await expect(a.query('UPDATE progress_notes SET content=$1 WHERE id=$2',['leak',note.id])).rejects.toThrow();const report=await run(()=>service.createReport({studentId:ids.student,enrollmentId:ids.enrollment,title:'Term',periodStart:'2026-01-01',periodEnd:'2026-12-31'}));await run(()=>service.publishReport(report.id));const snapshot=(await run(()=>service.getReport(report.id))).snapshot;const settled=await Promise.allSettled([run(()=>service.replaceReport(report.id,{teacherComment:'one'})),run(()=>service.replaceReport(report.id,{teacherComment:'two'}))]);expect(settled.filter(x=>x.status==='fulfilled')).toHaveLength(1);const replacement=(settled.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<any>).value;expect((await run(()=>service.getReport(report.id))).status).toBe('PUBLISHED');await run(()=>service.publishReport(replacement.id));expect((await run(()=>service.getReport(report.id))).status).toBe('SUPERSEDED');expect((await run(()=>service.getReport(report.id))).snapshot).toEqual(snapshot);});
 it('portal is published-only, excludes notes, blocks IDOR and cross-tenant IDs',async()=>{const student={id:ids.student,code:'S1',fullName:'Student',guardianSubjectIds:[ulid()],billingGuardianSubjectIds:[],studentSubjectIds:[]};const output=await context.run({tenant:meta,pool:a,portal:{students:[student],subjects:[]}} as TenantContext,()=>portal.get(ids.student));expect(output).toHaveProperty('summary');expect(output).toHaveProperty('assessments');expect(JSON.stringify(output)).not.toContain('private');await expect(context.run({tenant:meta,pool:a,portal:{students:[student],subjects:[]}} as TenantContext,()=>portal.get(ids.other))).rejects.toBeInstanceOf(NotFoundException);await expect(context.run({tenant:meta,pool:a,portal:{students:[student],subjects:[]}} as TenantContext,()=>portal.get(ids.cross))).rejects.toBeInstanceOf(NotFoundException);});
});
