import { api } from "@/lib/api";
import type { Assessment, AssessmentCriterion, Gradebook, GradebookInput, PortalProgress, ProgressNote, ProgressReport, ProgressReportInput, ReportSnapshot, StudentProgress } from "./types";

export const progressKey = (scope: string, id: string) => ["progress", scope, window.location.hostname, id] as const;
export const listAssessments = async (classId: string) => (await api.get<Assessment[]>(`/classes/${classId}/assessments`)).data;
export const createAssessment = async (classId: string, input: { title: string; type: Assessment["type"]; scoringMode: Assessment["scoringMode"]; maxScore: string; description?: string; assessmentDate?: string; criteria?: AssessmentCriterion[] }) => (await api.post<Assessment>(`/classes/${classId}/assessments`, input)).data;
export const getAssessment = async (id: string) => (await api.get<Assessment>(`/assessments/${id}`)).data;
export const updateAssessment = async (id: string, input: Partial<Assessment>) => (await api.patch<Assessment>(`/assessments/${id}`, input)).data;
export const updateCriteria = async (id: string, criteria: AssessmentCriterion[]) => (await api.put<Assessment>(`/assessments/${id}/criteria`, { criteria })).data;
export const getGradebook = async (id: string) => (await api.get<Gradebook>(`/assessments/${id}/gradebook`)).data;
export const updateGradebook = async (id: string, results: GradebookInput[]) => (await api.put<Assessment>(`/assessments/${id}/gradebook`, { results })).data;
export const publishAssessment = async (id: string) => (await api.post<Assessment>(`/assessments/${id}/publish`)).data;
export const archiveAssessment = async (id: string) => (await api.post<Assessment>(`/assessments/${id}/archive`)).data;
export const correctResult = async (id: string, input: { status?: "GRADED" | "EXEMPT"; score?: string; criterionScores?: Array<{ criterionId: string; score: string; comment?: string | null }>; comment?: string | null; reason: string }) => (await api.post(`/assessment-results/${id}/correct`, input)).data;
export const getStudentProgress = async (id: string) => (await api.get<StudentProgress>(`/students/${id}/progress`)).data;
export const getProgressNotes = async (id: string) => (await api.get<ProgressNote[]>(`/students/${id}/progress-notes`)).data;
export const createProgressNote = async (id: string, content: string) => (await api.post<ProgressNote>(`/students/${id}/progress-notes`, { content })).data;
export const getProgressReports = async (id: string) => (await api.get<ProgressReport[]>(`/students/${id}/progress-reports`)).data;
export const createProgressReport = async (input: { studentId: string; enrollmentId: string } & ProgressReportInput) => (await api.post<ProgressReport>("/progress-reports", input)).data;
export const updateProgressReport = async (id: string, input: Partial<ProgressReportInput>) => (await api.patch<ProgressReport>(`/progress-reports/${id}`, input)).data;
export const previewProgressReport = async (id: string) => (await api.get<ReportSnapshot>(`/progress-reports/${id}/preview`)).data;
export const publishProgressReport = async (id: string) => (await api.post<ProgressReport>(`/progress-reports/${id}/publish`)).data;
export const replaceProgressReport = async (id: string, input: Partial<ProgressReportInput>) => (await api.post<ProgressReport>(`/progress-reports/${id}/replacement`, input)).data;
export const getPortalProgress = async (id: string) => (await api.get<PortalProgress>(`/portal/students/${id}/progress`)).data;
