import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getApiErrorMessage } from "@/lib/api";
import { toast } from "sonner";
import { archiveAssessment, createAssessment, listAssessments, progressKey, publishAssessment } from "./api";
import type { AssessmentType } from "./types";

const labels = { DRAFT: "Bản nháp", PUBLISHED: "Đã công bố", ARCHIVED: "Đã lưu trữ" };
export function AssessmentSection({ classId, canWrite = false, canPublish = false }: { classId: string; canWrite?: boolean; canPublish?: boolean }) {
  const client = useQueryClient(); const [title, setTitle] = useState(""); const [type, setType] = useState<AssessmentType>("SIMPLE");
  const query = useQuery({ queryKey: progressKey("class-assessments", classId), queryFn: () => listAssessments(classId) });
  const create = useMutation({ mutationFn: () => createAssessment(classId, { title: title.trim(), type }), onSuccess: () => { setTitle(""); void client.invalidateQueries({ queryKey: progressKey("class-assessments", classId) }); toast.success("Đã tạo đánh giá nháp."); }, onError: (e) => toast.error(getApiErrorMessage(e, "Không thể tạo đánh giá.")) });
  const action = useMutation({ mutationFn: ({ id, kind }: { id: string; kind: "publish" | "archive" }) => kind === "publish" ? publishAssessment(id) : archiveAssessment(id), onSuccess: () => { void client.invalidateQueries({ queryKey: progressKey("class-assessments", classId) }); toast.success("Đã cập nhật đánh giá."); }, onError: (e) => toast.error(getApiErrorMessage(e, "Không thể cập nhật đánh giá.")) });
  return <section className="mt-7" aria-labelledby="class-assessments-heading"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 id="class-assessments-heading" className="m-0 text-lg font-semibold text-[#0f172a]">Đánh giá tiến độ</h2><p className="mt-1 mb-0 text-sm text-[#64748b]">Tạo đánh giá, nhập điểm tập trung và công bố kết quả.</p></div>{canWrite && <form className="flex flex-wrap gap-2" onSubmit={(e) => { e.preventDefault(); if (title.trim()) create.mutate(); }}><Input aria-label="Tên đánh giá" placeholder="Tên đánh giá" value={title} onChange={(e) => setTitle(e.target.value)} /><select aria-label="Loại đánh giá" className="input" value={type} onChange={(e) => setType(e.target.value as AssessmentType)}><option value="SIMPLE">Điểm số</option><option value="RUBRIC">Rubric</option></select><Button disabled={create.isPending || !title.trim()}>Tạo nháp</Button></form>}</div>{query.isPending ? <div className="state">Đang tải đánh giá…</div> : query.isError ? <div className="state error">Không thể tải đánh giá.</div> : !query.data?.length ? <div className="rounded-xl border border-[#e2e8f0] bg-white px-5 py-8 text-center text-sm text-[#64748b]">Chưa có đánh giá.</div> : <div className="overflow-x-auto rounded-xl border border-[#e2e8f0] bg-white"><table className="w-full text-left text-sm"><thead><tr><th className="px-4 py-3">Tên</th><th className="px-4 py-3">Loại</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Thao tác</th></tr></thead><tbody>{query.data.map((item) => <tr className="border-t border-[#f1f5f9]" key={item.id}><td className="px-4 py-3 font-semibold">{item.title}</td><td className="px-4 py-3">{item.type === "RUBRIC" ? "Rubric" : "Điểm số"}</td><td className="px-4 py-3">{labels[item.status]}</td><td className="flex flex-wrap gap-2 px-4 py-3"><Button variant="secondary" size="sm" asChild><Link to={`/assessments/${item.id}/gradebook`}>Sổ điểm</Link></Button>{canPublish && item.status === "DRAFT" && <Button size="sm" onClick={() => action.mutate({ id: item.id, kind: "publish" })}>Công bố</Button>}{canWrite && item.status === "PUBLISHED" && <Button variant="secondary" size="sm" onClick={() => action.mutate({ id: item.id, kind: "archive" })}>Lưu trữ</Button>}</td></tr>)}</tbody></table></div>}</section>;
}
