import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageContainer } from "@/components/page-container";
import { LoadingState } from "@/components/loading-state";
import { ErrorState } from "@/components/error-state";
import { getApiErrorMessage } from "@/lib/api";
import { toast } from "sonner";
import { getGradebook, progressKey, updateGradebook } from "./api";

export function GradebookPage() { const { id } = useParams(); const nav = useNavigate(); const client = useQueryClient(); const [values, setValues] = useState<Record<string, { score: string; feedback: string }>>({}); const query = useQuery({ queryKey: progressKey("gradebook", id ?? ""), queryFn: () => getGradebook(id!), enabled: Boolean(id) });
  const save = useMutation({ mutationFn: () => updateGradebook(id!, query.data!.students.map((student) => ({ ...student, score: values[student.studentId]?.score === "" ? null : Number(values[student.studentId]?.score ?? student.score ?? 0), feedback: values[student.studentId]?.feedback ?? student.feedback ?? "" }))), onSuccess: () => { void client.invalidateQueries({ queryKey: progressKey("gradebook", id ?? "") }); toast.success("Đã lưu sổ điểm."); }, onError: (e) => toast.error(getApiErrorMessage(e, "Không thể lưu sổ điểm.")) });
  if (query.isPending) return <PageContainer><LoadingState label="Đang tải sổ điểm" /></PageContainer>; if (query.isError || !query.data) return <PageContainer><ErrorState title="Không thể tải sổ điểm" message="Vui lòng thử lại." onRetry={() => void query.refetch()} /></PageContainer>;
  return <PageContainer><Button variant="ghost" asChild className="mb-4 -ml-3"><Link to={`/classes/${query.data.assessment.classId}`}>Quay lại lớp học</Link></Button><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="m-0 text-2xl font-bold text-[#0f172a]">{query.data.assessment.title}</h1><p className="mt-2 mb-0 text-sm text-[#64748b]">Sổ điểm tập trung · {query.data.assessment.type === "RUBRIC" ? "Rubric" : "Điểm số"}</p></div><Button disabled={save.isPending} onClick={() => save.mutate()}>{save.isPending ? "Đang lưu…" : "Lưu sổ điểm"}</Button></header><div className="overflow-x-auto rounded-xl border border-[#e2e8f0] bg-white"><table className="w-full text-left text-sm"><thead><tr><th className="px-4 py-3">Học viên</th><th className="w-36 px-4 py-3">Điểm</th><th className="px-4 py-3">Nhận xét</th></tr></thead><tbody>{query.data.students.map((student) => { const value = values[student.studentId] ?? { score: student.score?.toString() ?? "", feedback: student.feedback ?? "" }; return <tr className="border-t border-[#f1f5f9]" key={student.studentId}><td className="px-4 py-3 font-semibold">{student.studentName}<span className="ml-2 text-xs font-normal text-[#64748b]">{student.studentCode}</span></td><td className="px-4 py-3"><Input type="number" min="0" value={value.score} onChange={(e) => setValues((prev) => ({ ...prev, [student.studentId]: { ...value, score: e.target.value } }))} aria-label={`Điểm của ${student.studentName}`} /></td><td className="px-4 py-3"><Input value={value.feedback} onChange={(e) => setValues((prev) => ({ ...prev, [student.studentId]: { ...value, feedback: e.target.value } }))} aria-label={`Nhận xét cho ${student.studentName}`} /></td></tr>; })}</tbody></table></div></PageContainer>;
}
