import { useQuery } from "@tanstack/react-query";
import { getPortalProgress } from "./api";
import { PortalPage, QueryState, StudentSelector, useSelectedStudent } from "../portal/portal-ui";

export function PortalProgressPage() {
  const { me, student, select } = useSelectedStudent();
  const query = useQuery({ queryKey: ["portal", "progress", student?.id], queryFn: () => getPortalProgress(student!.id), enabled: Boolean(student) });
  return <PortalPage title="Tiến độ học tập" description="Chỉ hiển thị kết quả và báo cáo đã được trung tâm công bố."><QueryState query={me}>{me.data?.students.length && student ? <><StudentSelector student={student} students={me.data.students} onChange={select} /><QueryState query={query}>{query.data && <><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Chuyên cần", query.data.summary.attendanceRate == null ? "—" : `${query.data.summary.attendanceRate}%`], ["Điểm trung bình", query.data.summary.assessmentAverage ?? "—"], ["Đánh giá", query.data.summary.gradedAssessmentCount ?? 0], ["Buổi hoàn tất", query.data.summary.completedSessions ?? 0]].map(([label, value]) => <div className="rounded-xl border border-[#e2e8f0] bg-white p-4" key={label}><p className="m-0 text-xs text-[#64748b]">{label}</p><p className="mt-1 mb-0 text-xl font-bold text-[#0f172a]">{value}</p></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-[#e2e8f0] bg-white p-5"><h2 className="m-0 text-lg font-semibold">Kết quả đánh giá</h2>{query.data.assessments.length ? <div className="mt-4 divide-y divide-[#f1f5f9]">{query.data.assessments.map((item) => <article className="py-3 first:pt-0" key={item.id}><p className="m-0 font-semibold">{item.title}</p><p className="mt-1 mb-0 text-sm text-[#64748b]">{item.status === "EXEMPT" ? "Miễn đánh giá" : `Điểm: ${item.score ?? "—"}/${item.maxScore ?? "—"}`}</p>{item.comment && <p className="mt-1 mb-0 text-sm text-[#475569]">{item.comment}</p>}</article>)}</div> : <p className="mt-4 text-sm text-[#64748b]">Chưa có kết quả được công bố.</p>}</section><section className="rounded-xl border border-[#e2e8f0] bg-white p-5"><h2 className="m-0 text-lg font-semibold">Lịch sử báo cáo</h2>{query.data.reports.length ? <div className="mt-4 space-y-3">{query.data.reports.map((item, index) => <article className="rounded-lg bg-[#f8fafc] p-3" key={item.id}><div className="flex flex-wrap items-center justify-between gap-2"><p className="m-0 font-semibold">{item.title}</p><span className="text-xs text-[#64748b]">{index === 0 ? "Mới nhất" : "Phiên bản trước"}</span></div><p className="mt-1 mb-0 text-xs text-[#64748b]">{item.periodStart}–{item.periodEnd}{item.publishedAt ? ` · ${new Date(item.publishedAt).toLocaleDateString("vi-VN")}` : ""}</p>{item.snapshot?.narrative.teacherComment && <p className="mt-2 mb-0 whitespace-pre-wrap text-sm text-[#475569]">{item.snapshot.narrative.teacherComment}</p>}</article>)}</div> : <p className="mt-4 text-sm text-[#64748b]">Chưa có báo cáo được công bố.</p>}</section></div></>}</QueryState></> : null}</QueryState></PortalPage>;
}
